### ISSUE TITLE
TimeStampDigestMismatchException: Verification failed for property 'SignatureTimeStamp'

### ISSUE THREAD

**Issue by anyelahg** [luisgoncalves/xades4j#101]
Hello, I am trying to use xades4j library in a Java Web Service which verifies the XADES-C signature.

This web service works properly when the file and the timestamp uses the same digest algorithm, SHA-512. However, when the file uses SHA-512, and the tag CompleteCertificateRefs uses SHA-1, I get the following exception:

> xades4j.verification.TimeStampDigestMismatchException: Verification failed for property  SignatureTimeStamp': input digest and token message imprint mismatch

Here is the code from xades4j (xades4j.providers.impl.DefaultTimeStampVerificationProvider:173) which throws the exception:

`if(!Arrays.equals(md.digest(tsDigestInput), tsTokenInfo.getMessageImprintDigest())){
            throw new TimeStampTokenDigestException();
}`

Thanks in advance.

**Comment by luisgoncalves** [comment]
If I understood correctly, you're using xades4j to implement the web service. How's the signature file being generated? Also using xades4j?

You mention the `CompleteCertificateRefs` but this shouldn't impact `SignatureTimeStamp`, which is the property that is failing validation, according to the exception message...

What do you mean by "file uses SHA-512"? Is it the digest method for the reference over the file being signed? Can you post a sample signature file?

**Comment by anyelahg** [comment]
I don't generate the signature file, i get the signed file to validate it with Xades4j.
The signed file don't works when the SignatureMethod is "rsa-sha512", and the DigestMethod is "sha512" and also "sha1"
The signed file to works properly when the SignatureMethod is "rsa-sha512", and the DigestMethod "sha512" in the whole document.
I don't know if this should impact SignatureTimeStamp but it is the only difference.

[SAMPLEFILE_WITHERROR.xml.zip](https://github.com/luisgoncalves/xades4j/files/711019/SAMPLEFILE_WITHERROR.xml.zip)

**Comment by luisgoncalves** [comment]
It shouldn't impact `SignatureTimeStamp`. Are you sure that the signatures are being correctly generated? Maybe the change to SHA1 is somehow altering the digest used in the timestamp and something is output wrong on the file....

Can you debug the verification? If so, I suggest checking the digest algorithm extracted from the timestamp token by [DefaultTimeStampVerificationProvider](https://github.com/luisgoncalves/xades4j/blob/master/src/main/java/xades4j/providers/impl/DefaultTimeStampVerificationProvider.java#L166). Is it SHA-1 or SHA-512? If it is SHA-1 and you force the other on debug, does it succeed?

**Comment by anyelahg** [comment]
The signatures are being correctly generated, because the signed file was validated by another validator.

I am debugging and the digest algorithm extracted is it SHA-1, i forced it SHA-512, but i do not succeed.
Here my test:
`org.bouncycastle.tsp.TimeStampTokenInfo tsTokenInfo = tsToken.getTimeStampInfo();`
`try {`
`//String digestAlgUri = uriForDigest(tsTokenInfo.getMessageImprintAlgOID());`
`String digestAlgUri = "http://www.w3.org/2001/04/xmlenc#sha512";`
`MessageDigest md = messageDigestProvider.getEngine(digestAlgUri);`
`  if (!Arrays.equals(md.digest(tsDigestInput), tsTokenInfo.getMessageImprintDigest())) {`
`     throw new TimeStampTokenDigestException();`
`  }
 }`

**Comment by luisgoncalves** [comment]
When you validate a all SHA-512 file, is the extracted digest algorithm also SHA-512? It seems that when you use SHA-1, all the qualifying properties have that algorithm. Nevertheless, I'm running out of ideas, since everything works on the SHA-512 case...

Do you also control the production of signatures? We'd need to compare the digested input for the generation and validation of the timestamp token.

**Comment by luisgoncalves** [comment]
Any progress on this?

**Comment by anyelahg** [comment]
Hi Luis, I'm sorry for my late response, but I've had too much work.

Effectly when you validate a all SHA-512 file, the extracted digest algorithm also is SHA-512. Choose the algorithm depending on a code that searches on a map, so when you validate a all SHA-1 file, the extracted digest algorithm also is SHA-1

I don't have the control the production of signatures, but apparently the document is validated by more than one agent, then the tags of sha-512 and / or sha-1.
I can not understand why the arrays are different.

Thank you for your interest and help.

**Comment by luisgoncalves** [comment]
I'm not sure how I can be of further assistance... Sorry. This doesn't seem to be a bug on xades4j side.
