### ISSUE TITLE
 xades4j.providers.TimeStampTokenGenerationException: TSA returned HTTP 401 Unauthorized!

### ISSUE THREAD

**Issue by gk03k** [luisgoncalves/xades4j#104]
Hi,

I am using xades4j for default time stamping . I want to use new timestamp but no idea how to use it.

the code which prevois developer has developed is giving exception while signing the document .

Exception:
[
xades4j.production.PropertyDataGenerationException: Property data generation failed for SignatureTimeStamp: cannot get a time-stamp ]
[Caused by: xades4j.providers.TimeStampTokenGenerationException: TSA returned HTTP 401 Unauthorized at ades4j.providers.impl.DefaultTimeStampTokenProvider.getResponse(DefaultTimeStampTokenProvider.java:144)	at xades4j.providers.impl.DefaultTimeStampTokenProvider.getTimeStampToken(DefaultTimeStampTokenProvider.java:102)	at xades4j.production.DataGenBaseTimeStamp.generatePropertyData(DataGenBaseTimeStamp.java:60)]
]

Actually, first i signed my xml file attached here. After that our step to do 
is timestamping this signed xml from TSA (http://tss.accv.es:8318/tsa),which is a 
 for timestamping the document.

so to get timestamp they are using default time stamp provider like below.

code:
public class InhouseTimeStampProvider extends DefaultTimeStampTokenProvider {
	@Inject
	public InthouseTimeStampProvider(MessageDigestEngineProvider messageDigestProvider) {
		super(messageDigestProvider);
	}

	@Override
	public String getTSAUrl() {
		//return "https://www.safestamper.com/tsa" ;
		return "http://tss.accv.es:8318/tsa";
	}

As I have no idea about this TSA time stamp thus unable to identify issue..
	

So how i can timestamping the signed pdf file by using xades4j library?

Thanks & Regards
Ganesh

**Comment by luisgoncalves** [comment]
Any additional info? This exception probably mean that you need credentials to access the TSA.

**Comment by gk03k** [comment]
Sorry your reply was too quick... Thank you for that..I was still writing my query!!!!

I mentioned pdf document earlier ......actually its xml document.

the error I am getting in the code under below method.


 private Document signBillOfExchange(String xmlDocumentContent, Invoice invoice) throws Exception {

    	logger.info("inside signBillofExchange:::::");
	KeyingDataProvider buyerKeyingDataProvider = createKeyingProvider(invoice.getBuyer());
	logger.info("buyerKeyingDataProvider:::"+buyerKeyingDataProvider);
	Document document = CryptoUtil.signDocumentWithXADES_T(xmlDocumentContent, buyerKeyingDataProvider);
	
			return document;
    }

Could you please let me know if any other information required.

Kind Regards,
gk

**Comment by gk03k** [comment]
Hi Luis,
 As you said TSA access credential required. 
previously  I was using free tsa url and its working fine on my local system. but when I deploy the code on the linux server .. I am getting following exception.

[
 xades4j.production.PropertyDataGenerationException: Property data generation failed for SignatureTimeStamp: cannot get a time-stamp
xades4j.production.PropertyDataGenerationException: Property data generation failed for SignatureTimeStamp: cannot get a time-stamp]

Kind Regards,
gk

**Comment by luisgoncalves** [comment]
If your TSA requires credentials, you can use [AuthenticatedTimeStampTokenProvider](https://github.com/luisgoncalves/xades4j/wiki/Timestamping) (HTTP basic authentication only).

Regarding the error on the server, isn't that some connectivity issue? The "inner exceptions" will probably have the detailed cause. 

Anyway, this doesn't seem like a problem with the library. For this type of issues, in the future please use Stackoverflow (`xades4j` tag).

**Comment by luisgoncalves** [comment]
Any luck with this? I'm closing the issue. Reopen if you find any problems on the lib.

**Comment by gk03k** [comment]
Hi Luis,

Sorry for the delay in reply.

Yes it's worked fine for me. Thank you very much!

XadesSigningProfile profile = new XadesTSigningProfile(keyingDataProvider)
			.withTimeStampTokenProvider(new AuthenticatedTimeStampTokenProvider(
	                                new DefaultMessageDigestProvider(), 
	                                new TSAHttpAuthenticationData("*****", "*****", "*****")))
			.withAlgorithmsProviderEx(DefaultAlgorithmsProviderEx.class);

Regards,
gk
