### ISSUE TITLE
Allow to provide a validation date, for signatures not covered by timestamps.

### ISSUE THREAD

**Issue by gcontini** [luisgoncalves/xades4j#105]
I need to perform validations of some XAdES file for which the validation date is provided by an external source. These files have no timestamp.

This often happens in junits (when test certificates expire) or when the signature date can be provided by external sources such as detached timestamps, fields in database... (application requirements may vary).

At the moment i don't see any easy way to do this. The validation date for signatures not covered by timestamps is always now.

**Comment by luisgoncalves** [comment]
Agreed. The problem with unit tests is a smell since the start.

Do you have any implementation suggestion?
