### ISSUE TITLE
Update Santuario to 2.0.9+ to get a fix for getNodesetBeforeFirstCanonicalization()

### ISSUE THREAD

**Issue by luisgoncalves** [luisgoncalves/xades4j#113]
- https://issues.apache.org/jira/browse/SANTUARIO-462
- https://github.com/luisgoncalves/xades4j/pull/110/commits/98f8b5d1813ddd27042f993c4e567fe15914364b

**Comment by emmanvg** [comment]
Hi Luis,

I think the fix is already out. Hope this helps:

http://santuario.apache.org/download.html
https://mvnrepository.com/artifact/org.apache.santuario/xmlsec

Thanks,
Emmanuelle

**Comment by luisgoncalves** [comment]
Thanks!
