### ISSUE TITLE
document with two counter signatures can not verify 

### ISSUE THREAD

**Issue by witaste** [luisgoncalves/xades4j#116]
In my opinion , this document with two counter signatures should be verified ,but there is an exception:

xades4j.verification.CounterSignatureSigValueRefException: Verification failed for property 'CounterSignature': the counter signature doesn't reference the SignatureValue element of the countersigned signature
	at xades4j.verification.CounterSignatureVerifier.verify(CounterSignatureVerifier.java:79)

[document.signed.bes.c.txt](https://github.com/luisgoncalves/xades4j/files/1043884/document.signed.bes.c.txt)

**Comment by luisgoncalves** [comment]
By looking into the structure of the document, I agree. I'll have to try to reproduce this on my side. Do you have the setup code for the `CounterSignature` property? :)

**Comment by witaste** [comment]
yes ,here it is.
[testSignBESWithCounterSigCounterSig.txt](https://github.com/luisgoncalves/xades4j/files/1046541/testSignBESWithCounterSigCounterSig.txt)

[document.signed.bes.cs.cs.txt](https://github.com/luisgoncalves/xades4j/files/1046542/document.signed.bes.cs.cs.txt)

[failure trace.txt](https://github.com/luisgoncalves/xades4j/files/1046543/failure.trace.txt)

**Comment by luisgoncalves** [comment]
Fixed. It can be tested on the latest snapshot build
