### ISSUE TITLE
How to change Algorithms Method(http://www.w3.org/2001/04/xmldsig-more#rsa-sha512)

### ISSUE THREAD

**Issue by rich29698** [luisgoncalves/xades4j#121]
Xades4j default algorithms is http://www.w3.org/2001/04/xmldsig-more#rsa-sha256 
how to change algorithms to rsa-sha512

**Comment by luisgoncalves** [comment]
Check the documentation in the wiki:

https://github.com/luisgoncalves/xades4j/wiki/ChangingAlgorithms
