### ISSUE TITLE
Issue with FirstCertificateSelector()

### ISSUE THREAD

**Issue by juanp88** [luisgoncalves/xades4j#122]
Greetings, I'm having troubles signing a xml file with the xades-epes specification. I'm kind of a newbie with java but I need to get this done, I've found an example and I've been trying to make it work with my data but I get this error:

> Exception in thread "main" java.lang.NoClassDefFoundError: xades4j/providers/impl/FirstCertificateSelector
	at Signer.Main.signBes(Main.java:93)
	at Signer.Main.main(Main.java:72)
Caused by: java.lang.ClassNotFoundException: xades4j.providers.impl.FirstCertificateSelector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
> 

`package Signer;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.security.KeyStore;
import java.security.cert.X509Certificate;
import java.util.Collection;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.InputSource;
import xades4j.algorithms.EnvelopedSignatureTransform;
import xades4j.production.DataObjectReference;
import xades4j.production.SignedDataObjects;
import xades4j.production.XadesBesSigningProfile;
import xades4j.production.XadesEpesSigningProfile;
import xades4j.production.XadesSigner;
import xades4j.production.XadesTSigningProfile;
import xades4j.properties.DataObjectDesc;
import xades4j.properties.QualifyingProperty;
import xades4j.properties.SignatureTimeStampProperty;
import xades4j.properties.SigningCertificateProperty;
import xades4j.properties.SigningTimeProperty;
import xades4j.providers.CertificateValidationProvider;
import xades4j.providers.KeyingDataProvider;
import xades4j.providers.impl.AuthenticatedTimeStampTokenProvider;
import xades4j.providers.impl.DefaultMessageDigestProvider;
import xades4j.providers.impl.DirectPasswordProvider;
import xades4j.providers.impl.FileSystemKeyStoreKeyingDataProvider;
import xades4j.providers.impl.FirstCertificateSelector;
import xades4j.providers.impl.PKIXCertificateValidationProvider;
import xades4j.providers.impl.TSAHttpAuthenticationData;
import xades4j.utils.DOMHelper;
import xades4j.utils.FileSystemDirectoryCertStore;
import xades4j.verification.XAdESVerificationResult;
import xades4j.verification.XadesVerificationProfile;

public class Main {

    private static final String CERT_FOLDER = "/home/jperez/Documentos/factura_electronica";
    private static final String CERT        = "cert.pm";
    private static final String KEY_STORE   = "KeyStore";
    private static final String PASS        = "summan"; //the same in cert and keystorage

    private static final String TSA_URL     = "http://XXX.XXX.XXX/ts.inx";
    private static final String TSA_USER    = "XXXXXXXX";
    private static final String TSA_PASS    = "XXXXXXXX";

    private static final String UNSIGNED    = "/home/jperez/Documentos/factura_electronica/unsigned.xml";
    private static final String SIGNED      = "/home/jperez/Documentos/factura_electronica/signed-epes.xml";
    private static final String SIGNEDT     = "/home/jperez/Documentos/factura_electronica/signed-t-epess.xml";    
    private static final String VERIFY      = "/home/jperez/Documentos/factura_electronica/verify-epess.txt";
    private static final String VERIFYT     = "/home/jperez/Documentos/factura_electronica/verify-t-epes.txt";
    private static final String DOCUMENT    = "/home/jperez/Documentos/valid0.xml";
    private static final String DOCSIGNED   = "/home/jperez/Documentos/factura_electronica/signed.epes.xml";

    public static void main(String[] args) throws Exception {
        System.out.println("______________________");
        System.out.println("\tSign");
        System.out.println("______________________");
        signBes();
        
        System.out.println("______________________");
        System.out.println("\tVerify");
        System.out.println("______________________");
        verifyBes();

    }

    private static void signBes() throws Exception {
        Document doc = DocumentBuilderFactory
                .newInstance()
                .newDocumentBuilder()
                .parse(new File(DOCUMENT));
        Element elem = doc.getDocumentElement();
        DOMHelper.useIdAsXmlId(elem);
        

        KeyingDataProvider kdp = new FileSystemKeyStoreKeyingDataProvider(
                "jks",
                CERT_FOLDER + CERT,
                new FirstCertificateSelector(),
                new DirectPasswordProvider(PASS),
                new DirectPasswordProvider(PASS),
                true);
        DataObjectDesc obj = new DataObjectReference("#" + elem.getAttribute("Id"))
                .withTransform(new EnvelopedSignatureTransform());
        SignedDataObjects dataObjs = new SignedDataObjects().withSignedDataObject(obj);

        XadesSigner signer = new XadesEpesSigningProfile(kdp, PASS).newSigner();
        signer.sign(dataObjs, elem);

        TransformerFactory tFactory = TransformerFactory.newInstance();
        Transformer transformer = tFactory.newTransformer();
        DOMSource source = new DOMSource(doc);        
        StreamResult result = new StreamResult(new File(SIGNED));
        transformer.transform(source, result);
    }
`

**Comment by luisgoncalves** [comment]
Hello.

The `FirstCertificateSelector` is not part of the library itself; it is an helper class defined in the [test packages](https://github.com/luisgoncalves/xades4j/blob/master/src/test/java/xades4j/providers/impl/FirstCertificateSelector.java). You would need to copy it to your project.

Note that certificate selectors should be defined according to the specific use-case and the key stores in use.

Let me know if this helps.

**Comment by juanp88** [comment]
Thanks, that solve that error, I thought that I've imported everything the project needed but it was missing that class. Hopefully I would be able to make it the whole thing work.

**Comment by HanYw12** [comment]
Disculpa tengo un problema parecido no me sale el error que DirectPasswordProvider no pertenece al paquete 
<img width="473" alt="image" src="https://user-images.githubusercontent.com/67331821/212523555-f8419168-9933-474c-8925-57d2854f87db.png">

**Comment by luisgoncalves** [comment]
@HanYw12 the explanation is similar to the one in my previous messages regarding `FirstCertificateSelector`.

`DirectPasswordProvider` is not part of the library itself; it is an helper class defined in the  test packages. You should implement `KeyStoreKeyingDataProvider.KeyStorePasswordProvider` and `KeyStoreKeyingDataProvider.KeyEntryPasswordProvider` as needed. Or eventually copy `DirectPasswordProvider` to your project.
