### ISSUE TITLE
XadesEPES example

### ISSUE THREAD

**Issue by juanp88** [luisgoncalves/xades4j#125]
Hi, could anyone give an example on how to sign a document with the Xades EPES specification? I haven't been able to make it work.

Thanks

**Comment by luisgoncalves** [comment]
https://github.com/luisgoncalves/xades4j/blob/master/src/test/java/xades4j/production/SignerEPESTest.java

**Comment by luisgoncalves** [comment]
Did you manage to get it to work?

**Comment by juanp88** [comment]
Hi Luis, thanks for asking. I'm still having troubles, maybe I'm making some silly mistake but this is what I tried:
```
import xades4j.production.SignerEPESTest;

public class Firmador {
	
	public static void main (String[] args) {
		
		System.out.println("============================================================================");
		System.out.println("XADESTEST : EPES SIGNATURE");
		System.out.println("============================================================================");
		System.out.println();
		SignerEPESTest signerEPESTest = new SignerEPESTest();
		System.out.println("signerEPESTest : " + signerEPESTest.toString());
		/**
		* ==== NOT OK =====
		*/
		try {
			signerEPESTest.testSignEPES();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

}
```
and this is the error I get:

> java.lang.NullPointerException
> 	at xades4j.utils.XadesProfileCore.addBinding(XadesProfileCore.java:81)
> 	at xades4j.production.XadesSigningProfile.withBinding(XadesSigningProfile.java:149)
> 	at xades4j.production.XadesEpesSigningProfile.<init>(XadesEpesSigningProfile.java:51)
> 	at xades4j.production.SignerEPESTest.testSignEPES(SignerEPESTest.java:69)
> 	at Firma.main.main(main.java:19)

**Comment by luisgoncalves** [comment]
Uhm.. I pointed you to the test as an example on how to use the library... Please read the documentation in the wiki and then get back to the example.

**Comment by juanp88** [comment]
Hi, I read the wiki information and make this code for signing an xml file.

```
package Firma;

import java.io.ByteArrayInputStream;
import java.security.KeyStoreException;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;

import xades4j.algorithms.XPath2FilterTransform;
import xades4j.production.DataObjectReference;
import xades4j.production.Enveloped;
import xades4j.production.EnvelopedXmlObject;
import xades4j.production.SignerEPES;
import xades4j.production.SignerEPESTest;
import xades4j.production.XadesBesSigningProfile;
import xades4j.production.XadesEpesSigningProfile;
import xades4j.production.XadesSigner;
import xades4j.production.XadesSigningProfile;
import xades4j.properties.DataObjectDesc;
import xades4j.properties.IdentifierType;
import xades4j.properties.ObjectIdentifier;
import xades4j.properties.SignaturePolicyBase;
import xades4j.properties.SignaturePolicyIdentifierProperty;
import xades4j.providers.KeyingDataProvider;
import xades4j.providers.SignaturePolicyInfoProvider;
import xades4j.providers.impl.DirectPasswordProvider;
import xades4j.providers.impl.FileSystemKeyStoreKeyingDataProvider;
import xades4j.providers.impl.FirstCertificateSelector;
import xades4j.utils.SignatureServicesTestBase;
import xades4j.utils.XadesProfileResolutionException;

public class main extends SignatureServicesTestBase {
	
	public static void main (String[] args) throws Exception {
		
		//establezco la politica de firma
		
		SignaturePolicyInfoProvider policyInfoProvider = new SignaturePolicyInfoProvider()
        {
           
            public SignaturePolicyBase getSignaturePolicy()
            {
                return new SignaturePolicyIdentifierProperty(
                        new ObjectIdentifier("oid:/1.2.4.0.9.4.5", IdentifierType.OIDAsURI, "Policy description"),
                        new ByteArrayInputStream("Test policy input stream".getBytes()))
                    .withLocationUrl("http://www.example.com/policy");
            }
        };
		
        //ingreso la información de los certificados
        
		KeyingDataProvider kp = new FileSystemKeyStoreKeyingDataProvider(
                "pkcs12",
                "/home/jperez/Documentos/certificados/cert_key.p12",
                new FirstCertificateSelector(),
                new DirectPasswordProvider("summan2017"),
                new DirectPasswordProvider("summan2017"),
                true);
		
		//crea el perfil de firma xades
		
		XadesSigningProfile p = new XadesEpesSigningProfile(kp, policyInfoProvider);
				
		Document doc = getTestDocument();
        Element elemToSign = doc.getDocumentElement();
        
        SignerEPES signer = (SignerEPES)new XadesEpesSigningProfile(kp, policyInfoProvider).newSigner();
        new Enveloped(signer).sign(elemToSign);
        outputDocument(doc, "document.signed.epes.xml");
        
}

	
	private static Document getTestDocument() throws Exception {
		 return getDocument("document.xml");		
	}

}
```
this is the error message I get:

> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

what I'm doing wrong?

**Comment by juanp88** [comment]
Hola Luis,

Leí el wiki y esto fue lo que hice:

package Firma;

import java.io.ByteArrayInputStream;
import java.security.KeyStoreException;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;

import xades4j.algorithms.XPath2FilterTransform;
import xades4j.production.DataObjectReference;
import xades4j.production.Enveloped;
import xades4j.production.EnvelopedXmlObject;
import xades4j.production.SignerEPES;
import xades4j.production.SignerEPESTest;
import xades4j.production.XadesBesSigningProfile;
import xades4j.production.XadesEpesSigningProfile;
import xades4j.production.XadesSigner;
import xades4j.production.XadesSigningProfile;
import xades4j.properties.DataObjectDesc;
import xades4j.properties.IdentifierType;
import xades4j.properties.ObjectIdentifier;
import xades4j.properties.SignaturePolicyBase;
import xades4j.properties.SignaturePolicyIdentifierProperty;
import xades4j.providers.KeyingDataProvider;
import xades4j.providers.SignaturePolicyInfoProvider;
import xades4j.providers.impl.DirectPasswordProvider;
import xades4j.providers.impl.FileSystemKeyStoreKeyingDataProvider;
import xades4j.providers.impl.FirstCertificateSelector;
import xades4j.utils.SignatureServicesTestBase;
import xades4j.utils.XadesProfileResolutionException;

public class main extends SignatureServicesTestBase {

    public static void main (String[] args) throws Exception {

        //establezco la politica de firma

        SignaturePolicyInfoProvider policyInfoProvider = new
SignaturePolicyInfoProvider()
        {

            public SignaturePolicyBase getSignaturePolicy()
            {
                return new SignaturePolicyIdentifierProperty(
                        new ObjectIdentifier("oid:/1.2.4.0.9.4.5",
IdentifierType.OIDAsURI, "Policy description"),
                        new ByteArrayInputStream("Test policy input
stream".getBytes()))
                    .withLocationUrl("http://www.example.com/policy");
            }
        };

        //ingreso la información de los certificados

        KeyingDataProvider kp = new FileSystemKeyStoreKeyingDataProvider(
                "pkcs12",
                "/home/jperez/Documentos/certificados/cert_key.p12",
                new FirstCertificateSelector(),
                new DirectPasswordProvider("summan2017"),
                new DirectPasswordProvider("summan2017"),
                true);

        //crea el perfil de firma xades

        XadesSigningProfile p = new XadesEpesSigningProfile(kp,
policyInfoProvider);

        Document doc = getTestDocument();
        Element elemToSign = doc.getDocumentElement();

        SignerEPES signer = (SignerEPES)new XadesEpesSigningProfile(kp,
policyInfoProvider).newSigner();
        new Enveloped(signer).sign(elemToSign);
        outputDocument(doc, "document.signed.epes.xml");

}


    private static Document getTestDocument() throws Exception {
         return getDocument("document.xml");
    }

}

y este es el error que me saca:


SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further
details.

Que estoy haciendo mal?

2017-10-17 13:40 GMT-05:00 Luís Gonçalves <notifications@github.com>:

**Comment by luisgoncalves** [comment]
Not sure.. Do you have the stack trace? I don't know what the error about the logger might be.

**Comment by juanp88** [comment]
No... thats the only thing I get on console. Does my code make sense to you?

**Comment by luisgoncalves** [comment]
The code seems fine. I'm not sure the error comes from xades4j. Can't you try/catch and see the stack trace??

**Comment by juanp88** [comment]
I tried it but I've got nothing,  I put some prints so I could see where the error starts, and as far as I can tell all the code is executed but I don't get my xml signed.
```
package Firma;

import java.io.ByteArrayInputStream;
import java.security.KeyStoreException;

import javax.xml.transform.Result;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamResult;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;

import xades4j.algorithms.XPath2FilterTransform;
import xades4j.production.DataObjectReference;
import xades4j.production.Enveloped;
import xades4j.production.EnvelopedXmlObject;
import xades4j.production.SignerEPES;
import xades4j.production.SignerEPESTest;
import xades4j.production.XadesBesSigningProfile;
import xades4j.production.XadesEpesSigningProfile;
import xades4j.production.XadesSigner;
import xades4j.production.XadesSigningProfile;
import xades4j.properties.DataObjectDesc;
import xades4j.properties.IdentifierType;
import xades4j.properties.ObjectIdentifier;
import xades4j.properties.SignaturePolicyBase;
import xades4j.properties.SignaturePolicyIdentifierProperty;
import xades4j.providers.KeyingDataProvider;
import xades4j.providers.SignaturePolicyInfoProvider;
import xades4j.providers.impl.DirectPasswordProvider;
import xades4j.providers.impl.FileSystemKeyStoreKeyingDataProvider;
import xades4j.providers.impl.FirstCertificateSelector;
import xades4j.utils.SignatureServicesTestBase;
import xades4j.utils.XadesProfileResolutionException;

public class main extends SignatureServicesTestBase {
	
	public static void main (String[] args) throws Exception {
		
		System.out.println("Aqui empieza el codigo");
		
		//establezco la politica de firma
		
		SignaturePolicyInfoProvider policyInfoProvider = new SignaturePolicyInfoProvider()
        {
           
            public SignaturePolicyBase getSignaturePolicy()
            {
                return new SignaturePolicyIdentifierProperty(
                        new ObjectIdentifier("oid:/1.2.4.0.9.4.5", IdentifierType.OIDAsURI, "Policy description"),
                        new ByteArrayInputStream("Test policy input stream".getBytes()))
                    .withLocationUrl("http://www.example.com/policy");
            }
        };
		
        //ingreso la información de los certificados
        
		KeyingDataProvider kp = new FileSystemKeyStoreKeyingDataProvider(
                "pkcs12",
                "/home/jperez/Documentos/certificados/cert_key.p12",
                new FirstCertificateSelector(),
                new DirectPasswordProvider("summan2017"),
                new DirectPasswordProvider("summan2017"),
                true);
		
		//crea el perfil de firma xades
		
		XadesSigningProfile p = new XadesEpesSigningProfile(kp, policyInfoProvider);
				
		Document doc = getTestDocument();
        Element elemToSign = doc.getDocumentElement();
        System.out.println("inicia el firmador");
        try {
			SignerEPES signer = (SignerEPES)new XadesEpesSigningProfile(kp, policyInfoProvider).newSigner();
			System.out.println("Enveloped");
			new Enveloped(signer).sign(elemToSign);
			outputDocument(doc, "document.signed.epes.xml");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}         
        System.out.println("documento creado");
}

	
	private static Document getTestDocument() throws Exception {
		 return getDocument("document.xml");		
	}

}

```

> Aqui empieza el codigo
> inicia el firmador
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> Enveloped
> documento creado
>

**Comment by juanp88** [comment]
Hi, i solved it the code is fine I just needed to change the path of the outputdirectory. I forgot to do that.
Thanks

**Comment by homerocapo** [comment]
In xades4j-1.3.2.jar, not include DirectPasswordProvider and FirstCertificateSelector. 
![Uploading image.png…]()
What can be wrong?
