### ISSUE TITLE
Any example how to create a Xades epes signature using .p12 certificate?

### ISSUE THREAD

**Issue by mau-nm** [luisgoncalves/xades4j#132]
do you have any example where I can see how to create a Xades epes signature using .p12 certificate?

**Comment by luisgoncalves** [comment]
- Example for XAdES EPES on unit tests: https://github.com/luisgoncalves/xades4j/blob/master/src/test/java/xades4j/production/SignerEPESTest.java
- For a p12 file containg cert/key you should be able to use the `FileSystemKeyStoreKeyingDataProvider` as described here: https://github.com/luisgoncalves/xades4j/wiki/DefiningKeyingData

**Comment by mau-nm** [comment]
Thanks @luisgoncalves
