### ISSUE TITLE
Error keyinfo' cannot be validated

### ISSUE THREAD

**Issue by FuriosoJack** [luisgoncalves/xades4j#138]
Hello I am signed my xml with your application, the entity to which I sent it also uses its software to validate the signatures but I receive the following error from them,

```
java.exception.msg | com.indra.mmdd.signature.exceptions.ValidateException: xades4j.verification.ReferenceValueException: Reference '#xmldsig-20835b91-f45f-4bd4-bff0-94afa92125bd-keyinfo' cannot be validated
-- | --

```
Could you tell me what can cause this error

**Comment by luisgoncalves** [comment]
It's hard to tell without any further info from the validation process... Can you get more details?
