### ISSUE TITLE
InMemory KeyStore Builder Question!

### ISSUE THREAD

**Issue by edennish** [luisgoncalves/xades4j#140]
Hi Luis,

Sorry for writing this here, but I didn't find another place to put the question.

I have a question about the KeyStore, is it possible to use instead of a file a variable with the key database? 

I'm thinking about developing a service (with jetty) that receives the parameters and the certificate and be able to use it from a variable, not a file.

I tried to implement something like:

    public MemoryKeyStoreKeyingDataProvider(
            final String keyStoreType,
            final byte[] certificate,
            SigningCertSelector certificateSelector,
            KeyStorePasswordProvider keyStorePasswordProvider,
            KeyEntryPasswordProvider entryPasswordProvider,
            boolean returnFullChain)
    {
        super(new KeyStoreBuilderCreator()
        {
            @Override
            public Builder getBuilder(ProtectionParameter loadProtection)
            {
                
                return KeyStore.Builder.newInstance(
                        keyStoreType,
                        null,
                        new ByteArrayInputStream(certificate),    <<----- HERE!!!!
                        loadProtection);
            }
        },
                certificateSelector,
                keyStorePasswordProvider,
                entryPasswordProvider,
                returnFullChain);
    }

But as you may know, that doesn't work.

Any advice?

Best regards.

**Comment by luisgoncalves** [comment]
It seems that the Builder API doesn't have an option to supply an `InputStream`...  So I guess you have two options:

1. Save the certificate/key file into a temporary location and use that on your code above.
2. Don't extend the `KeyStoreKeyingDataProvider` class; create a new one that uses `KeyStore.load()` method, which allows you to supply an `InputStream`. If you know the password in advance you can even simplify the implementation and avoid the `KeyStorePasswordProvider` and `KeyEntryPasswordProvider` altogether.

Let me know if this helps.

**Comment by edennish** [comment]
Excellent! It works like a charm!

public MemoryKeyStoreKeyingDataProvider(
            final String keyStoreType,
            final InputStream certificate,
            SigningCertSelector certificateSelector,
            KeyStorePasswordProvider keyStorePasswordProvider,
            KeyEntryPasswordProvider entryPasswordProvider,
            boolean returnFullChain)
    {
        super(new KeyStoreBuilderCreator()
        {
            @Override
            public Builder getBuilder(ProtectionParameter loadProtection) 
            {
                KeyStore ks = null;
                try {
                    ks = KeyStore.getInstance(keyStoreType);
                    ks.load(certificate, keyStorePasswordProvider.getPassword() );
                } catch (KeyStoreException ex) {
                    Logger.getLogger(MemoryKeyStoreKeyingDataProvider.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(MemoryKeyStoreKeyingDataProvider.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NoSuchAlgorithmException ex) {
                    Logger.getLogger(MemoryKeyStoreKeyingDataProvider.class.getName()).log(Level.SEVERE, null, ex);
                } catch (CertificateException ex) {
                    Logger.getLogger(MemoryKeyStoreKeyingDataProvider.class.getName()).log(Level.SEVERE, null, ex);
                }
                return  KeyStore.Builder.newInstance(ks, loadProtection);
                
            }
        },
                certificateSelector,
                keyStorePasswordProvider,
                entryPasswordProvider,
                returnFullChain);
    }
