### ISSUE TITLE
How to add <ds:XPath>not(ancestor - or - self::ds:Signature)</ds:XPath>?

### ISSUE THREAD

**Issue by osgroupCR** [luisgoncalves/xades4j#141]
Hi experts, 

How can I include the following transform and SignedDataObjectProperties MimeType sections in a Xades-EPES Enveloped signature: 

Transform: 

<ds:Reference Id="rid1" URI="">
        <ds:Transforms>
          <ds:Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116">
            <ds:XPath>not(ancestor-or-self::ds:Signature)</ds:XPath>
          </ds:Transform>
          <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"></ds:Transform>
        </ds:Transforms>
        <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"></ds:DigestMethod>
        <ds:DigestValue>...</ds:DigestValue>
      </ds:Reference>
 

SignedDataObjectProperties:
<xades:SignedDataObjectProperties>
            <xades:DataObjectFormat ObjectReference="#rid1">
              <xades:MimeType>application/octet-stream</xades:MimeType>
            </xades:DataObjectFormat>
          </xades:SignedDataObjectProperties>

Thanks in advance!

**Comment by luisgoncalves** [comment]
Hello,

For this type of questions, S.O. is the correct option.

Anyway, did you read the documentation?

- https://github.com/luisgoncalves/xades4j/wiki/SignatureProduction
  - In your case you want to start with [XadesEpesSigningProfile](http://luisgoncalves.github.io/xades4j/javadocs/1.4.0/reference/xades4j/production/XadesEpesSigningProfile.html)
- [Define signed resources and add properties and transforms](https://github.com/luisgoncalves/xades4j/wiki/DefiningSignedResources)
  - [DataObjectFormatProperty](http://luisgoncalves.github.io/xades4j/javadocs/1.4.0/reference/xades4j/properties/DataObjectFormatProperty.html)
  - [XPath transform](http://luisgoncalves.github.io/xades4j/javadocs/1.4.0/reference/xades4j/algorithms/XPathTransform.html)

**Comment by osgroupCR** [comment]
Thanks @luisgoncalves 

I can successfully sign the xml using: 
 new Enveloped(signer)
              .sign(elemToSign);

however, for DataObjectFormatProperty if I use something like: 
DataObjectDesc obj1 = new DataObjectReference("").withDataObjectFormat(new DataObjectFormatProperty("application/octet-stream"));
SignedDataObjects dataObjs = new SignedDataObjects(obj1);
signer.sign(dataObjs, elemToSign);
it does created the SignedDataObjectProperties for the referenced URI="" but it doesn't create the enveloped signature. How can I combine both using new Eveloped(signer)? 

Thanks!

**Comment by luisgoncalves** [comment]
You can't.

The `Enveloped` class only supports straightforward scenarios (probably shouldn't have been included in the library). You can manually add the [`EnvelopedSignatureTransform`](http://luisgoncalves.github.io/xades4j/javadocs/1.4.0/reference/xades4j/algorithms/EnvelopedSignatureTransform.html) to the `DataObjectReference`.

**Comment by osgroupCR** [comment]
ok I see your point, 

the following line is giving me a correct digest in reference-1, however is failing in reference-2 (as per etsi checker). Is the line structure correct or am I missing something? 

DataObjectDesc obj1 = new DataObjectReference("").withDataObjectFormat(new DataObjectFormatProperty("application/octet-stream")).withTransform(new XPathTransform("not(ancestor-or-self::ds:Signature)")).withTransform(new EnvelopedSignatureTransform());

as usual thanks a ton!

**Comment by osgroupCR** [comment]
nvm, I needed to set setNamespaceAware(true);

Thank you! this is a great tool!
