### ISSUE TITLE
Problem w/ child nodes of QualifyingProperties when validating

### ISSUE THREAD

**Issue by andreslugo** [luisgoncalves/xades4j#142]
Hello,
while im trying to validate a XAdES-BES Enveloping signature, Xades4j is throwing an exception because "SignedProperties not found as the first child of QualifyingProperties". There is no option to find the SignedProperties tag? Using https://valide.redsara.es/valide/ for signature validation, it says that the signature is valid. It is true that SignedProperties is not the first child tag, because the signature Generator we are using is introducing an empty UnsignedProperties tag first but this does not make the signature invalid.

I attached the signature that is causing this exception. Regards,

Andrés
[firmaEjemplo.zip](https://github.com/luisgoncalves/xades4j/files/1598147/firmaEjemplo.zip)

P.D: we are using version n. 1.3.2

**Comment by luisgoncalves** [comment]
Hello,

Actually, accordingly to [XAdES schema](https://www.w3.org/TR/XAdES/#Syntax_overview_The_QualifyingProperties), the XML is invalid.  It has to be a sequence and that's probably why it is failing.

Can you copy the stack trace here? I'd say the error comes from XML deserialization (JAXB).

**Comment by luisgoncalves** [comment]
Please reopen if you have additional information.
