### ISSUE TITLE
Spaces on X509Certificate

### ISSUE THREAD

**Issue by dcortes22** [luisgoncalves/xades4j#143]
Hello I'm using this code to generate a Xades Sign:

`System.out.println("Aqui empieza el codigo");
            //establezco la politica de firma
            SignaturePolicyInfoProvider policyInfoProvider = new SignaturePolicyInfoProvider() {
                public SignaturePolicyBase getSignaturePolicy() {
                    return new SignaturePolicyIdentifierProperty(
                            new ObjectIdentifier("https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica"),
                            new ByteArrayInputStream("Politica de Factura Digital".getBytes()));
                }
            };

            //ingreso la información de los certificado
            KeyingDataProvider kp = new FileSystemKeyStoreKeyingDataProvider("pkcs12", "src/011397011030-2.p12", new FirstCertificateSelector(),
                    new DirectPasswordProvider("3006"),
                    new DirectPasswordProvider("3006"),
                    true);

            DataObjectDesc obj1 = new DataObjectReference("").withDataObjectFormat(new DataObjectFormatProperty("application/octet-stream")).withTransform(new XPathTransform("not(ancestor-or-self::ds:Signature)")).withTransform(new EnvelopedSignatureTransform());

            SignedDataObjects dataObjs = new SignedDataObjects(obj1);

            //crea el perfil de firma xades
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            factory.setNamespaceAware(true);
            DocumentBuilder builder = null;
            builder = factory.newDocumentBuilder();
            InputSource is = new InputSource(new StringReader("<FacturaElectronica xmlns=\"https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica\"><Clave>50601011800011397011000100001010000000007130182346</Clave><NumeroConsecutivo>00100001010000000046</NumeroConsecutivo><FechaEmision>01-01-2018T13:50:24-06:00</FechaEmision><Emisor><Nombre>David Cortes Saenz</Nombre><Identificacion><Tipo>01</Tipo><Numero>113970110</Numero></Identificacion><NombreComercial>David Cortes Saenz</NombreComercial><Ubicacion><Provincia>1</Provincia><Canton>01</Canton><Distrito>01</Distrito></Ubicacion><Telefono><CodigoPais>506</CodigoPais><NumTelefono></NumTelefono></Telefono></Emisor><Receptor><Nombre>Daniel Cortes Saenz</Nombre><Identificacion><Tipo>01</Tipo><Numero>11111111111</Numero></Identificacion><IdentificacionExtranjero>0</IdentificacionExtranjero><Telefono><CodigoPais>506</CodigoPais><NumTelefono>34254352352</NumTelefono></Telefono><CorreoElectronico>d@d.com</CorreoElectronico></Receptor><CondicionVenta>01</CondicionVenta><MedioPago>01</MedioPago><DetalleServicio><LineaDetalle><NumeroLinea>1</NumeroLinea><Codigo><Tipo>02</Tipo><Codigo>002</Codigo></Codigo><Cantidad>5</Cantidad><UnidadMedida>un</UnidadMedida><UnidadMedidaComercial>Unidades</UnidadMedidaComercial><Detalle>Servicios Profesionales</Detalle><PrecioUnitario>20000</PrecioUnitario><MontoTotal>100000</MontoTotal><MontoDescuento>0</MontoDescuento><NaturalezaDescuento>0%</NaturalezaDescuento><SubTotal>100000</SubTotal><Impuesto><Codigo>01</Codigo><Tarifa>13</Tarifa><Monto>13000</Monto></Impuesto><MontoTotalLinea>113000</MontoTotalLinea></LineaDetalle></DetalleServicio><ResumenFactura><CodigoMoneda>CRC</CodigoMoneda><TipoCambio>576.7400</TipoCambio><TotalServGravados>0</TotalServGravados><TotalServExentos>0</TotalServExentos><TotalMercanciasGravadas>0</TotalMercanciasGravadas><TotalMercanciasExentas>0</TotalMercanciasExentas><TotalGravado>100000</TotalGravado><TotalExento>0</TotalExento><TotalVenta>100000</TotalVenta><TotalDescuentos>0</TotalDescuentos><TotalVentaNeta>0</TotalVentaNeta><TotalImpuesto>13000</TotalImpuesto><TotalComprobante>113000</TotalComprobante></ResumenFactura><Normativa><NumeroResolucion>DGT-R-48-2016</NumeroResolucion><FechaResolucion>07-10-2016 00:00:00</FechaResolucion></Normativa></FacturaElectronica>"));
            Document doc1 = builder.parse(is);
            Element elemToSign = doc1.getDocumentElement();
            XadesSigningProfile p = new XadesEpesSigningProfile(kp, policyInfoProvider);
            XadesSigner signer = p.newSigner();

            signer.sign(dataObjs, elemToSign);

            //new Enveloped(signer).sign(elemToSign);
            Transformer transformer = TransformerFactory.newInstance().newTransformer();
            Result output = new StreamResult(new File("firmado.xml"));
            Source input = new DOMSource(doc1);
            transformer.transform(input, output);

            Document doc = null;
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            dbf.setNamespaceAware(true);
            DocumentBuilder db = dbf.newDocumentBuilder();
            doc = db.parse(new File("firmado.xml"));

            String value = toString(doc);

            String two = Base64.encodeBase64String(value.getBytes());

            System.out.println(two);

            System.out.println("documento creado");`

The problem is the result file has a weird white spaces on the X509Certificate section  

<img width="1242" alt="screen shot 2018-01-06 at 8 21 22 pm" src="https://user-images.githubusercontent.com/1170942/34645989-1c9b70e2-f322-11e7-800b-42232c606d41.png">

What are I'm doing wrong?

**Comment by luisgoncalves** [comment]
That seems just a problem of the viewer/reader you're using. 

Creating an issue is not very appropriate for this kind of questions. Use the `xades4j` tag on Stackoverflow, as it also reaches more people.
