### ISSUE TITLE
Verify Signature Failed

### ISSUE THREAD

**Issue by nutty151** [luisgoncalves/xades4j#147]
Hi,

I'm using Xades4j to sign my XML . XML can sign in Xades format but when I verify I got

The signature is not valid:
Reference URI="#xmldsig-76abea2a-67cf-4f69-a735-348c40a16e9b-signedprops" failed to verify
Validation of <SignedInfo> failed]

Here is the Code that I use for signing.

 Document doc = DocumentBuilderFactory
	                    .newInstance()
	                    .newDocumentBuilder()
	                    .parse(new File(fileEntry.getAbsolutePath()));
	            Element elem = doc.getDocumentElement();
	            
	           DOMHelper.useIdAsXmlId(elem);
	           	           	           	          
	            KeyingDataProvider kdp = new PKCS11KeyStoreKeyingDataProvider(
	                    "D:\\eTPKCS11.dll",
	                    "etoken",
	                    new FirstCertificateSelector(),
	                    new DirectPasswordProvider("Password"),  new DirectPasswordProvider("Password"), false);
	            
	           /* System.out.println("ID" + elem.getAttribute("Id"));*/
	            	           	           
	            DataObjectDesc obj = new DataObjectReference("").withTransform(new EnvelopedSignatureTransform());
	            SignedDataObjects dataObjs = new SignedDataObjects().withSignedDataObject(obj);	            	            	         
	            
	            
	               XadesSigningProfile p = new XadesBesSigningProfile(kdp);
	            XadesSigner signer = p.newSigner();
	            
	            signer.sign(dataObjs, elem);
	            
	            

	            TransformerFactory tFactory = TransformerFactory.newInstance();
	            Transformer transformer = tFactory.newTransformer();
	            DOMSource source = new DOMSource(doc);        
	            FileOutputStream result = new FileOutputStream(new File("D:\\out\\enc\\" + fileEntry.getName()));
	            transformer.transform(source, new StreamResult(result));
	            result.close();
	            System.out.println("Signed Completed");

Thanks you.

[TestSigned.zip](https://github.com/luisgoncalves/xades4j/files/1638602/TestSigned.zip)

**Comment by luisgoncalves** [comment]
Did you try setting `SetNamespaceAware` to true in the document builder factory? (both singing and verification)

**Comment by nutty151** [comment]
@luisgoncalves  Thankyou for fast response.

Sorry, I'm new on this. Where can I set the SetNamespaceAware to True before signing. 

Thank you.

**Comment by luisgoncalves** [comment]
Example here: https://github.com/luisgoncalves/xades4j/blob/master/src/test/java/xades4j/utils/SignatureServicesTestBase.java#L45

**Comment by nutty151** [comment]
@luisgoncalves  Thank you.

I change my code to

 DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
	            dbf.setNamespaceAware(true);
	            DocumentBuilder dbs = dbf.newDocumentBuilder();
	            
	            Document doc = dbs.parse(new File(fileEntry.getAbsolutePath()));

And now It's Valid.

Thank you very much.
