### ISSUE TITLE
SignerBes method sign, call 100% cpu and loading on macos

### ISSUE THREAD

**Issue by dns1984** [luisgoncalves/xades4j#148]
Under debugging, the application just hangs on this line
signer.sign(dataObjects, nodeToSign); 
and the application hangs
          

      final X509Certificate cert = (X509Certificate) keyStore.getCertificate(
                        signInfo.getAlias());

                final KeyingDataProvider keyingProvider = new DirectKeyingDataProvider(cert, privateKey);
                final XadesSigningProfile sigProf = new XadesTSigningProfile(keyingProvider)

                        // time-stamp provider. Дополнительно задается список соответствий между
                        // алгоритмом хеширования и адресом TSP службы, чтобы разнообразить и
                        // расширить пример.
                        .withTimeStampTokenProvider(new GostTimeStampTokenProvider(
                                digest2TsaUrlMap, JCP.PROVIDER_NAME))

                        // digest provider
                        .withDigestEngineProvider(new DefaultMessageDigestProvider() { // digest

                            @Override
                            public MessageDigest getEngine(String digestAlgorithmURI) throws UnsupportedAlgorithmException {
                                final String digestAlgOid = GostXAdESUtility.digestUri2Digest(digestAlgorithmURI);
                                try {
                                    MessageDigest md = MessageDigest.getInstance(digestAlgOid);
                                    return md;
                                } catch (NoSuchAlgorithmException e) {
                                    throw new UnsupportedAlgorithmException(e.getMessage(), digestAlgorithmURI, e);
                                }
                            }

                        })

                        .withAlgorithmsProviderEx(new DefaultAlgorithmsProviderEx() { // algorithms

                            private String digestUrn = null;

                            @Override
                            public Algorithm getSignatureAlgorithm(String keyAlgorithmName)
                                    throws UnsupportedAlgorithmException {
                                digestUrn = GostXAdESUtility.key2DigestUrn(keyAlgorithmName);
                                final String signatureUrn = GostXAdESUtility.key2SignatureUrn(keyAlgorithmName);

                                return new GenericAlgorithm(signatureUrn);
                            }

                            @Override
                            public String getDigestAlgorithmForReferenceProperties() {
                                return digestUrn;
                            }

                            public String getDigestAlgorithmForDataObjsReferences() {
                                return digestUrn;
                            }

                            public String getDigestAlgorithmForTimeStampProperties() {
                                return digestUrn;
                            }

                            @Override
                            public Algorithm getCanonicalizationAlgorithmForSignature() {
                                return new ExclusiveCanonicalXMLWithoutComments();
                            }

                            @Override
                            public Algorithm getCanonicalizationAlgorithmForTimeStampProperties() {
                                return new ExclusiveCanonicalXMLWithoutComments();
                            }

                        });

                final XadesSigner signer = sigProf.newSigner();
                final DataObjectDesc dataObj = new DataObjectReference(referenceURI);
                dataObj.withTransform(new EnvelopedSignatureTransform());
                final SignedDataObjects dataObjects = new SignedDataObjects(dataObj);
                signer.sign(dataObjects, nodeToSign); --Freeze!!!

**Comment by luisgoncalves** [comment]
What's the "referenceUri" that you are using?

I don't have any way to test this in macOS. Can you try breaking the debugger to see where the execution is blocked?

**Comment by luisgoncalves** [comment]
Any news on this?

**Comment by luisgoncalves** [comment]
Reopen if you have more specific info and/or solutions.
