### ISSUE TITLE
No issuer certificate error in XAdES verify

### ISSUE THREAD

**Issue by M4rkB** [luisgoncalves/xades4j#158]
Hi,

Thank you for your huge job with xades and for share it with everyone. I'm trying to do a xades verification but I can't and maybe you will know the reason.

The problem is when I do "XAdESVerificationResult r = v.verify(sigElem, null);".

It appears this error: 

> xades4j.providers.CannotBuildCertificationPathException: No issuer certificate for certificate in certification path found.	
> at xades4j.providers.impl.PKIXCertificateValidationProvider.validate(PKIXCertificateValidationProvider.java:257)
> at xades4j.verification.XadesVerifierImpl.verify(XadesVerifierImpl.java:175)

I did a lot of times and with different ways the creation of the keystore from .crt and when I list the certificate it tells me that the certificates are there:

![image](https://user-images.githubusercontent.com/41780939/43313167-8f6b54dc-918f-11e8-8995-83d791db51d8.png)

This is my code, but I think that it's ok:

        String SIGNED   = "C:/Cert/signed_bes.xml";
    	String CERT_FOLDER = "C:/Cert/";
    	String KEY_STORE = "keystore.jks";
    	PASS = "certbo";
    	
    	try {    		
    		DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        	factory.setNamespaceAware(true);
        	DocumentBuilder builder = factory.newDocumentBuilder();
        	Document doc = builder.parse(new InputSource(new FileReader(SIGNED)));
        	NodeList nl = doc.getElementsByTagName("ds:Signature");        	
        	FileSystemDirectoryCertStore certStore = new FileSystemDirectoryCertStore(CERT_FOLDER);
        	KeyStore ks = null;
        	
        	try (FileInputStream fis = new FileInputStream(CERT_FOLDER + KEY_STORE)) {
        		ks = KeyStore.getInstance("jks");
        		ks.load(fis,PASS.toCharArray());
        	} catch (CertificateException e) {
    			e.printStackTrace();
    		} catch (KeyStoreException e) {
    			e.printStackTrace();
    		}
        	
        	CertificateValidationProvider provider = new PKIXCertificateValidationProvider(ks, false, certStore.getStore());        	
        	XadesVerificationProfile profile = new XadesVerificationProfile(provider);        	
        	Element sigElem = (Element)nl.item(0);
        	XadesVerifier v = profile.newVerifier();        	
        	XAdESVerificationResult r = v.verify(sigElem, null);
        	
        	log.info("************************ VerifyBes aconseguida!!!!! ************************");
        	System.out.println("Signature form: " + r.getSignatureForm());
            System.out.println("Algorithm URI: " + r.getSignatureAlgorithmUri());
            System.out.println("Signed objects: " + r.getSignedDataObjects().size());
            System.out.println("Qualifying properties: " + r.getQualifyingProperties().all().size());
            log.info(r.getSignedDataObjects());         
		
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {			
			e.printStackTrace();
		} catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		} catch (NoSuchProviderException e) {
			e.printStackTrace();
		} catch (CertificateException e1) {
			e1.printStackTrace();
		} catch (CRLException e1) {
			e1.printStackTrace();
		} catch (ParserConfigurationException e1) {
			e1.printStackTrace();
		} catch (SAXException e1) {
			e1.printStackTrace();
		} catch (XadesProfileResolutionException e) {
			e.printStackTrace();
		} catch (XAdES4jException e) {
			e.printStackTrace();
		} 

What do you think that is the problem? Is necessary do something special with the keystore?

Thanks for advance

Marc

**Comment by luisgoncalves** [comment]
Hello and thank you!

Regarding your issue, it's hard to say without more info. Other than the root CA, what certificates are present in the signature and the "CERT_FOLDER"? Are you sure that they build up a valid certification path?

**Comment by luisgoncalves** [comment]
Any news on this @M4rkB ? Did you manage to solve the problem?

**Comment by luisgoncalves** [comment]
Please reopen if needed.
