### ISSUE TITLE
 in the signature the <ds: Reference URI = "# keyinfoID"> tag is not found. DIAN of Colombia rejects the signature. Luis, please help me. Thank you.

### ISSUE THREAD

**Issue by rdvv94** [luisgoncalves/xades4j#161]
Hi Luis, I hope you are well, in the signing process I am not added to the keyinfoID and the Dian rejects me the request
<ds:Reference URI="#keyinfoID">
              <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
              <ds:DigestValue>76SlDTb1qbfuRRCx7GFcttgJ+QY=</ds:DigestValue>
            </ds:Reference>

**Comment by luisgoncalves** [comment]
Also, try reading through #151 and #134, as both issues have a lot of information on producing signatures for DIAN.
