### ISSUE TITLE
xades verification using embeded x509 certificate issue 

### ISSUE THREAD

**Issue by fgonzalezs** [luisgoncalves/xades4j#165]
I don't know if you have any comment or suggestions for this type of scenario.

wait for your comments.

Thanks

**Comment by luisgoncalves** [comment]
Can you provide more details? What do you mean by "embedded"? In the verifying app or in the signature?

**Comment by fgonzalezs** [comment]
Let me explain you, we don't want to use a keystore or certstore for validate our xml, we need to get the certificate and public key that is in the signed xml and proceed with the validation. I was checking issue #37 and #165 and they probably were looking that I am asking but I don't know if you have a solution or comment for these kind of scenarios.

**Comment by luisgoncalves** [comment]
Issue #117 mentions a SO question, which is [this one](https://stackoverflow.com/questions/44432054/xades4j-verification-issue-with-embeded-x509-certyificate). I added some explanation there of how xades4j already considers the certificates in `KeyInfo` when trying to validate the signature.

To verify the signature **value** the public key / certificate is used. Another step is validating the certificate itself, i.e. **building up a chain of trust**. In xades4j, this last step is represented by the [`CertificateValidationProvider`](http://luisgoncalves.github.io/xades4j/javadocs/1.4.0/reference/xades4j/providers/CertificateValidationProvider.html) interface. There is a builtin implementation ([`PKIXCertificateValidationProvider`](http://luisgoncalves.github.io/xades4j/javadocs/1.4.0/reference/xades4j/providers/impl/PKIXCertificateValidationProvider.html)). To which you can supply a keystore with trusted certification authorities (the roots of the chain).

If you want to directly trust a specific signing certificate, I suggest implementing a custom `CertificateValidationProvider` and [configure it on the verification profile](http://luisgoncalves.github.io/xades4j/javadocs/1.4.0/reference/xades4j/verification/XadesVerificationProfile.html#XadesVerificationProfile(xades4j.providers.CertificateValidationProvider)). Certificates present in the signature and selection criteria for the signing certificate are passed as arguments to `validate ` method. 

Hope this helps.

**Comment by fgonzalezs** [comment]
thanks.

**Comment by luisgoncalves** [comment]
Reopen if any problem arises.
