### ISSUE TITLE
Migrate to BouncyCastle Api for parsing/working with certificates

### ISSUE THREAD

**Issue by nekkiy** [luisgoncalves/xades4j#167]
Need migrate to BC Api for the reason that it provides more flexibile, extensible and manual-drived functional. Also it will have provided crossplatform for differents JDK implementations.

See [Issues-166](https://github.com/luisgoncalves/xades4j/issues/166), [Issues-107](https://github.com/luisgoncalves/xades4j/issues/107)

**Comment by nekkiy** [comment]
See [Issues-166)](https://github.com/luisgoncalves/xades4j/issues/166), See [Issues-107)](https://github.com/luisgoncalves/xades4j/issues/107)

**Comment by nekkiy** [comment]
I could make it, if we schedule version **2.0**, because this may be  incompabilityes API. It will be longer process, but current problems require it.

P. S. I offer version **2.0** without link to XADES specification number

**Comment by luisgoncalves** [comment]
I'm not sure this is needed as a whole. The problems identified so far are only related to comparison of DNs names. Also, on #166, loading certificates with the BC provider doesn't solve the issue, so migrating would need tototally replace the types in use (e.g. Java's `X509Certificate`) with BC's types (e.g. certificate holder), which is too big of a change to rush into.

I'd prefer seeing the outcome of #166 and let this idea mature for a while.

**Comment by luisgoncalves** [comment]
The mentioned issues were either solved or are dormant, so I don't see a strong reason to do this change. Closing for now.
