### ISSUE TITLE
la DIAN no me recibe ninguna factura 

### ISSUE THREAD

**Issue by Mariluz08** [luisgoncalves/xades4j#170]
@jsandrea88 He enviado muchas facturas a la DIAN pero siempre me las rechaza, me saca el siguiente error 

com.indra.mmdd.signature.exceptions.ValidateException: xades4j.verification.ReferenceValueException: Reference '#xmldsig-88fbfc45-3be2-4c4a-83ac-0796e1bad4c5-signedprops' cannot be validated

me puedes ayudar?

**Comment by alfaser123** [comment]
Mariluz lo pudiste resolver???
