### ISSUE TITLE
Unfortunately, there's a TSA CRL on test data that needs to be manually updated from time to time to ensure all the tests pass. If you pull the latest version it should be fine (a PR was merged yesterday that already includes the update).

### ISSUE THREAD

**Issue by aaronsaescobar** [luisgoncalves/xades4j#180]
Please reopen if the you still have any issues after that.

_Originally posted by @luisgoncalves in https://github.com/luisgoncalves/xades4j/issues/179#issuecomment-437573770_

thx but the problem persist after the update. if you need something let me know

![captura](https://user-images.githubusercontent.com/44914266/48306146-732caf80-e4fc-11e8-9be7-cfbb454ec439.PNG)

**Comment by luisgoncalves** [comment]
Follow up on the original issue. Reopened it.
