### ISSUE TITLE
Reference 'rfc3161.txt' cannot be validated

### ISSUE THREAD

**Issue by alfaser123** [luisgoncalves/xades4j#181]
with mvn package I get this error,. No clue how to resolved it..please help

**Comment by alfaser123** [comment]
I found the problem it is  http://www.ietf.org/rfc/rfc3161.txt must be changed to https://www.ietf.org/rfc/rfc3161.txt

**Comment by alfaser123** [comment]
Hi Luis
I found the URL changed. I did manualy on the browser but running mvn package again now I get a different error.
 
Caused by: org.apache.xml.security.signature.MissingResourceFailureException: The Reference for URI rfc3161.txt has no XMLSignatureInput
Original Exception was org.apache.xml.security.signature.ReferenceNotInitializedException: Could not find a resolver for URI rfc3161.txt and Base https://www.ietf.org/rfc/

**Comment by luisgoncalves** [comment]
It seems that the Apache Santuario resolver for HTTP URIs [doesn't support HTTPS](https://github.com/apache/santuario-java/blob/xmlsec-2.0.9/src/main/java/org/apache/xml/security/utils/resolver/implementations/ResolverDirectHTTP.java#L233)... 

It's probably better to change that test to depend on a more controlled URL. I'll try to do that soon.

**Comment by luisgoncalves** [comment]
@alfaser123 This should be fixed if you pull the latest version

**Comment by alfaser123** [comment]
Luis

I have been trying for weeks to sign a document with xades_epes, as a matter of fact I am not familiar with Java, i develope with  python and oracle forms but not at all with java. The not signed xml is generated from python.  I have been using netbeans but I get several problems. I  beg your help since you are the creator of xades4j to get a faster and direct solution for my need. Please contact me at alfaser@hotmail.com to get  a monetary agreement or if you have someone else who can work on my need.

Thanks

Andrés
alfaser@hotmail.com
________________________________
De: Luís Gonçalves <notifications@github.com>
Enviado: miércoles, 19 de diciembre de 2018 10:58 p. m.
Para: luisgoncalves/xades4j
CC: alfaser123; State change
Asunto: Re: [luisgoncalves/xades4j] Reference 'rfc3161.txt' cannot be validated (#181)


Closed #181<https://github.com/luisgoncalves/xades4j/issues/181> via d6d5fdb<https://github.com/luisgoncalves/xades4j/commit/d6d5fdb9b0987c266fb1829f533e7b7a6c45f3dc>.

**Comment by luisgoncalves** [comment]
Hello @alfaser123,

What exactly are you trying to accomplish? Where are you integrating xades4j? A web application? A forms application?

What are the requirements for your EPES signature in terms of signed resources ("references")? [This ticket](https://github.com/luisgoncalves/xades4j/issues/134) has a lot of info on creating a XAdES-EPES including source code (although in a different context).
