### ISSUE TITLE
How to create zip for the dian server xml to send the invoices

### ISSUE THREAD

**Issue by hemalDodiyaN** [luisgoncalves/xades4j#183]
I am working in Java , i have successfully implemented this xades standards for the signing the xml invoice now i want to send the zip through soap web service from my code but there is error occur because of zip which i create for the xml so please suggest me how to do that

**Comment by luisgoncalves** [comment]
This project is not associated to DIAN. You don't seem to be having any issue with xades4j, so this issue tracker is likely not the proper place for your question.

**Comment by hemalDodiyaN** [comment]
Okay Sorry For that
