### ISSUE TITLE
SigningCertificateReferenceNotFoundException

### ISSUE THREAD

**Issue by deepthi2889** [luisgoncalves/xades4j#188]
Hi,

I am trying to sign xml in Xades EPS format.

I have developed applications on both .Net and PHP for this signing purpose.

The xml signed from .Net code gets successfully verified at the receiver's end.

But the xml signed usign PHP code is failing validation with the following error.

com.indra.mmdd.signature.exceptions.ValidateException: xades4j.verification.SigningCertificateReferenceNotFoundException: Verification failed for property 'SigningCertificate': Couldn't find a reference to the signing certificate CN=xxxxxxxxx,C=xx,1.2.840.113549.1.9.1=#xxxxxxxxxxxxxxxxxxxxx,L=xxxxxxxxxxxxxxx,O=xxxxxxxxxxxx,1.3.6.1.4.1.23267.2.3=#xxxxxxxxxxxxxxxxxxxxx,2.5.4.5=#xxxxxxxxxxxxxxxx,OU=xxxxxxxxxxxxxxxxxxxxx,ST=xxxxxxxxxxxxxxxxxxxxx

What am I doing wrong here.

When the same xml is signed from .net code, it is successfully verified. Only PHP code is failing.

Please help me to resolve this issue.

**Comment by luisgoncalves** [comment]
Hi,

This issue tracker doesn't belong to `com.indra.mmdd.signature`. The fact that that project uses xades4j internally doesn't mean this is the proper place to get support. From what you said, your code doesn't even use xades4j (as it is .NET and PHP)...

That said, the error message seems pretty straightforward: the `SigningCertificate` property needs to contain a "reference" (issuer/serial and digest) of the singing certificate, which doesn't seem to be the case. Either that or the reference is being incorrectly built.
