### ISSUE TITLE
Consult about SignatureValue

### ISSUE THREAD

**Issue by angelcantu84** [luisgoncalves/xades4j#190]
Hi luisgoncaves.

Your work is awesome, thanks for share this excellent work.

I have a cuestion about how do you make the SignatureValue content?, Im working in a personal library on other language programming and I have problems to make the correct SignatureValue content.

For example this: https://github.com/luisgoncalves/xades4j/blob/master/src/test/xml/document.signed.epes_1.xml

What are you signing or putting on the SignatureValue ?

Regards !

**Comment by luisgoncalves** [comment]
Hi @angelcantu84 and thank you for the feedback.

In xades4j the `SignatureValue` is calculated by Apache Santuario, the underlying XML-DSIG library. The actual value is calculated according to a set of rules defined in the XML-DSIG spec. I already described this and provided links on [this comment on another issue](https://github.com/luisgoncalves/xades4j/issues/186#issuecomment-471929923) (It seems that the user deleted his comments... but it's still understandable). Hope this helps.
