### ISSUE TITLE
eDocument Spain: XADES-EPES - Validation Error

### ISSUE THREAD

**Issue by jSinnhh** [luisgoncalves/xades4j#194]
Dear Luis, first of thanks for your great contribution of Xades4j.
While using it it seems to me more powerful than first expected.

Well I am no java-guru therefore providing a good solution takes some time :)
We produce a sigend xml-document on base of some incoices given a the source xml.
But when trying to validate the file we receive:
Signature is Invalid
Number of Reference Digests = 3
Reference 1 digest is invalid because the computed digest differs from the digest in the XML.
Reference 2 digest is invalid because the computed digest differs from the digest in the XML.
Reference 3 digest is invalid because the computed digest differs from the digest in the XML.

Well that's a hard start i know, but starting with the signature we need to provide:
	<ds:Signature Id="Signature-c82218a3-f6d1-4645-95df-feabf07a2942-Signature" xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
		<ds:SignedInfo>
			<ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
			<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha512"/>
			<ds:Reference Id="Reference-2fc41fd8-260d-4978-8109-e6fb0d0cb70f" Type="http://www.w3.org/2000/09/xmldsig#Object" URI="">
		<ds:Transforms>
					<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
				</ds:Transforms>
				<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha512"/>
				<ds:DigestValue>N5Rth4ot0hMC0OTV6x39i8DbEGLHkSKeoiKiV2vr+BccRjO7ruWhJxXUDDq0NzGBefuT8inL7rWnkYqSosLs3w==</ds:DigestValue>
			</ds:Reference>
			<ds:Reference Type="http://uri.etsi.org/01903#SignedProperties" URI="#Signature-c82218a3-f6d1-4645-95df-feabf07a2942-SignedProperties">
				<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha512"/>
				<ds:DigestValue>dALlOP9mxpA4cGcx15k78RwmI1/NepfnNqvJMp9OkN6RU1mAV7hjg1GzzbSg86eHOqj8JSe6TNx50KzkJh71mQ==</ds:DigestValue>
			</ds:Reference>
			<ds:Reference URI="#Signature-c82218a3-f6d1-4645-95df-feabf07a2942-KeyInfo">
			<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha512"/>
<ds:DigestValue>P3gKhZL5KMfgwg8YMPw+arvv+lTcwM1krrUZ4qdNqQdCGUmPBMS/h11Qygu/SRF3G+G43SEzBHrrXHOv6IvvgQ==</ds:DigestValue>
			</ds:Reference>
		</ds:SignedInfo>
		<ds:SignatureValue Id="**Signature-c82218a3-f6d**1-4645-95df-feabf07a2942-SignatureValue">D8u4PvDvVtzMHxPWdWS0b4Bbky2z+8tlc5gnO5y5LM5DhB0dzoXjCGBe085xCpNiNWsQ6ek+LYmPihht2wZkJh8oIybCwltzzHH8I/Q+5YVirqGL34rqjJi8/w+3QBpJpGv0YcDrur1jD7LA0qPE84fExOJGjkl7/rdx2rwSxMIZzltX1hMw9blpqAwMbsHuSriYmXiGE1yvhrpbMfbkZt2l4O3OypJuR69VWn1oZbvfZg/l7F6BybSHK5qqstRm7VZDhvMvO8AmsjJrWg9rqdfJBJJeu45O7l2DguqY5QntqINmytUZxiMwYUkLmfDvv7wC4JiI2xhrgfUm5tXItQ==</ds:SignatureValue>

we produce:
<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="xmldsig-861df19d-810d-4250-aa3b-a1e365a43b6c">
<ds:SignedInfo>
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha512"/>
<ds:Reference Id="xmldsig-861df19d-810d-4250-aa3b-a1e365a43b6c-ref0" URI="">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha512"/>
<ds:DigestValue>tIdSB1stR+Px2F/JjUAO5CbHgHN4ht7K//AtLr6mJZvr5YfVh+xscQUbZsZWtuWIGB2m5/vO3yyi&#13;
wBG6v2hXAw==</ds:DigestValue>
</ds:Reference>
<ds:Reference URI="#xmldsig-861df19d-810d-4250-aa3b-a1e365a43b6c-keyinfo">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha512"/>
<ds:DigestValue>BJ/aloyQYAcOfCCP5F2KGEVfzMpkFkM5keT83RNP9uUm0YWk+EGKXtF0DAm1oKPI7cvclCpi0KZE&#13;
g3kRqoIuGg==</ds:DigestValue>
</ds:Reference>
<ds:Reference Type="http://uri.etsi.org/01903#SignedProperties" URI="#xmldsig-861df19d-810d-4250-aa3b-a1e365a43b6c-signedprops">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha512"/>
<ds:DigestValue>D6Y6rkSLFho0Ixd0pxclZ/ZXJEiIUfE3LWrvZLNA9oJ3aU5wM0wiRBiOv8pzjnyqXkv/aVlpK3ov&#13;
fZPduIaKQg==</ds:DigestValue>
</ds:Reference>
</ds:SignedInfo>
<ds:SignatureValue Id="**xmldsig-861df19d-810d-4250-aa**3b-a1e365a43b6c-sigvalue">
jx7ar9ksfSCUJiMsI17WpvSopPloapV3jZp4uPEkqkKPIpaUwtDtDt1W61zvb2/m+ik4kKzhGa8R&#13;
TYEZTyVC38uDuIBLN2GR00zlUDn2uB1dgVOhOzY/weJCEF46HentBApDqMUarRh2Mwe+IhsFVxhw&#13;
BVc2soSGj2Msb6Lm5BpYLz+BQ+LGlQ87VWBB5e8iljboOxk88878gmX4MwM3dKPpLg8WM4BQHp5T&#13;
3R34i7QyvYUAC5XixMcW0UZwBTyAHBQ230mYeQj9M1rCDQok1TA1tlmfWByLeJccAYKr68Q61wWk&#13;
hUFK6GSWuwh/vBTgIfaURI3fewx4lmvHMaxOOg==
</ds:SignatureValue>

Following code we are using:
`SignedDataObjects dataObjs = new SignedDataObjects().withSignedDataObject(obj);

		SignaturePolicyInfoProvider policyInfoProvider = new SignaturePolicyInfoProvider()
        {
           
            public SignaturePolicyBase getSignaturePolicy()
            {
            	        return new SignaturePolicyIdentifierProperty(
                        new ObjectIdentifier("http://www.facturae.es/politica_de_firma_formato_facturae/politica_de_firma_formato_facturae_v3_1.pdf"),
//                        new ByteArrayInputStream("Test policy input stream".getBytes())
                        new ByteArrayInputStream("src/politica_de_firma_formato_facturae_v3_1.pdf".getBytes())
                        );
            }
        };
		

		@SuppressWarnings("deprecation")
		XadesSigner signer = new XadesEpesSigningProfile(kdp,policyInfoProvider)
				
			.withSignaturePropertiesProvider
				(new SignaturePropertiesProvider() 
			{
//			setting SignaturProperties
			@Override
	        public void provideProperties(SignaturePropertiesCollector arg0){ 
			
	        	SigningTimeProperty sigTime = new SigningTimeProperty();
	            arg0.setSignerRole(new SignerRoleProperty().withClaimedRole("emisor"));
	            arg0.setSigningTime(sigTime);
			}
			}	
						
			).withAlgorithmsProviderEx(
				
				new AlgorithmsProviderEx() {
			@Override
	        public Algorithm getSignatureAlgorithm(String string) throws UnsupportedAlgorithmException {
//		           return new GenericAlgorithm(SignatureMethod.RSA_SHA1);
				return new GenericAlgorithm("http://www.w3.org/2001/04/xmldsig-more#rsa-sha512");
			}
			@Override
			public Algorithm getCanonicalizationAlgorithmForSignature() {
//				return new GenericAlgorithm(Canonicalizer.ALGO_ID_C14N_EXCL_OMIT_COMMENTS);
				return new GenericAlgorithm(Canonicalizer.ALGO_ID_C14N_OMIT_COMMENTS);
			}
			@Override
			public Algorithm getCanonicalizationAlgorithmForTimeStampProperties() {
				//return new GenericAlgorithm(Canonicalizer.ALGO_ID_C14N_EXCL_OMIT_COMMENTS);
//				return new GenericAlgorithm(Canonicalizer.ALGO_ID_C14N_OMIT_COMMENTS);
				return null;
			}
			public String getDigestAlgorithmForDataObjsReferences() {
				// TODO Auto-generated method stub
//				return Constants.ALGO_ID_DIGEST_SHA1;
				return MessageDigestAlgorithm.ALGO_ID_DIGEST_SHA512;
			}
			@Override
			public String getDigestAlgorithmForReferenceProperties() {
				// TODO Auto-generated method stub
//				return null;
				return Constants.ALGO_ID_DIGEST_SHA1;
				
			}
			@Override
			public String getDigestAlgorithmForTimeStampProperties() {
				// TODO Auto-generated method stub
				return Constants.ALGO_ID_DIGEST_SHA1;
//				return null;
			}
		}
			).withDataObjectPropertiesProvider(new DataObjectPropertiesProvider() {
				
				@Override
				public void provideProperties(DataObjectDesc arg0) {
					// TODO Auto-generated method stub
					arg0.getSignedDataObjProps();
					arg0.getUnsignedDataObjProps();
					
				}
			}).				
				withBasicSignatureOptionsProvider(new BasicSignatureOptionsProvider() {
				
				@Override
				public boolean signSigningCertificate() {
					// TODO Auto-generated method stub
					return true;
				}
				
				@Override
				public boolean includeSigningCertificate() {
					// TODO Auto-generated method stub
					return true;
				}
				
				@Override
				public boolean includePublicKey() {
					// TODO Auto-generated method stub
					return true;
				}
			})
				
			
				.newSigner();`

Point is: How to change the Signature Id for example?! Why does it start with **xmldsig-** etc.?!

Any help is appreciated. Thanks in advance!!

**Comment by luisgoncalves** [comment]
Hi. I really couldn't understand what the problem is nor what you're trying to accomplish.

- The code/text are poorly formatted and mixed-up.
- Are you generating or verifying a signature with xades4j?
- `xmldsig-....` is the structure of element id's generated by xades4j, but I see that you have others

**Comment by jSinnhh** [comment]
Hi Luis, thanks for your response - and yes - it is hard to read.

Ok, we have the situation that we need to generate a signature based on a node in an xml-file (invoices). This development will be used in a middleware for processing the data automatically to a webservice (signed).

There is also a tool provided be the webservice provider (authority) where the source xml (invoices) can be processed, signed and send to the webservice manually. Here we can get a signed output file as reference to check wether our development 'fit the specification'.

So let's start with a comparison of the produced Signature-Part:

**Tool** output is: 
<ds:Signature Id="Signature-c82218a3-f6d1-4645-95df-feabf07a2942-Signature" xmlns:ds="http://www.w3.org/2000/09/xmldsig#">

**Xades4j** output is:
<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="xmldsig-524bbf49-258c-4a43-99be-2f74752a7af3">

So xades produces a different Id - whereas I do not know if this might raise any issues verfiying the signature. How can we manipuate this output for the id?!

The authority also provide a webpage for verfiying the signed xml, saying:
Signature is Invalid
Number of Reference Digests = 3
Reference 1 digest is invalid because the computed digest differs from the digest in the XML.
Reference 2 digest is invalid because the computed digest differs from the digest in the XML.
Reference 3 digest is invalid because the computed digest differs from the digest in the XML.

Thanks, J

**Comment by luisgoncalves** [comment]
There's no way to change the generation of IDs. xades4j ensures they are unique and used correctly where needed.

Regarding the validation errors, since you aren't validating with xades4j, I don't know exactly how to help... One possible cause would be that the XML is modified after signing. How are you actually using the `XadesSigner`? How are you reading the source XML? How are you writing the signed XML?

**Comment by jSinnhh** [comment]
[signer.txt](https://github.com/luisgoncalves/xades4j/files/3546279/signer.txt)
Please find attached some code-example.

currently we read the source as file from server whereas in this xml-file is a node called FACTURAE which contains the invoices a base64 string. This is decoded by java and afterwards processed with xades4j.

see:
`NodeList facturaElems = dummyDoc.getElementsByTagName("FACTURA");
		Node facturaElem = facturaElems.item(1); 
		byte[] bytesFe = org.apache.commons.codec.binary.Base64.decodeBase64(facturaElem.getTextContent().getBytes("UTF-8")); 
		String facturaString = new String (bytesFe);`

For testing we write the signed-xml on the same server as xml via _Transformer_

**Comment by luisgoncalves** [comment]
I still don't get it and I'm pretty sure this isn't an issue with xades4j. You're probably mangling some encoding or similar.

- Is `dummyDoc` the same document where the signature will be appended?
- How is `facturaString` used? Is it XML itself?
- Can you show how you configure the signed data object with xades4j (`obj`)?

**Comment by jSinnhh** [comment]
ok - i attached the MainDocument.xml - here you see the dummy tag which we receive from sender (ERP). this tag is replaced at the end. the invoices are placed in the 2nd tag FACTURA base64 coded.

I hope that facturaString is XML because it is the byte-represantation of the decoded base64-FACTURA-Tag

Last one is a good question because I am not sure if we do this right. the config of `obj` is done this way:

`
public static Document signDocument(Document doc) throws Exception {
[..]
Element elem = doc.getDocumentElement();
DataObjectDesc obj = new DataObjectReference
		(elem.getAttribute("Invoices")
			)
[..]
`
Hope this helps understanding the scenario.

Kind regards

**Comment by luisgoncalves** [comment]
Wow, now I'm even more confused. In this last code snippet there a 2nd `Document`... This is where the signature is added, correct? Is this the `Document` that results from loading `facturaString`? Why not load it directly from the decoded base64 bytes? What a weird scenario.

Anyway, what are you exactly trying to sign? Is the content of that `"Invoices"` attribute a proper same-document reference pointing to the element you want to sign?

Sorry, but I'm close to giving up here. Your scenario is very confusing and you are providing scattered information. So far, nothing seems to show a problem with xades4j.

**Comment by jSinnhh** [comment]
Well the scenario is messed up due to some specifications we have to handle because they need to be considered said by spanish authority. 

Ok, maybe you can give me some help for these questions concerning xades4j:

a. Because of using DOM could it be that the signing might differ for plain xml vs. indent xml (again: I am no java-guru)
b. I erased some codepage issues and due to this fact one digest of three is finally identical to one of the reference-XML sigend by the tool/app given by the authority
c. How to erase some Transforms-Tags in the Reference-Tags - because the reference-XML looks different at some point
d. How to add this part to the qualifying properties.
`					<xades:SignedDataObjectProperties>
						<xades:DataObjectFormat ObjectReference="#Reference-2fc41fd8-260d-4978-8109-e6fb0d0cb70f">
							<xades:Description/>
							<xades:ObjectIdentifier>
								<xades:Identifier Qualifier="OIDAsURN">urn:oid:1.2.840.10003.5.109.10</xades:Identifier>
								<xades:Description/>
							</xades:ObjectIdentifier>
							<xades:MimeType>text/xml</xades:MimeType>
							<xades:Encoding/>
						</xades:DataObjectFormat>
					</xades:SignedDataObjectProperties>`

e. How to change the DigestMethod in SignaturePolicyIdentifier - SigPolicyHash. We need _http://www.w3.org/2000/09/xmldsig#sha1_ - but getting _http://www.w3.org/2001/04/xmlenc#sha512_

f. If I check `DataObjectDesc obj = new DataObjectReference
							(elem.getAttribute("Invoices")` 
I get 'null' back. Therefore I doubt that this works properly. So do we have to use an attribute or can we go with a node of the document?! And again - indent or single string?! And how to create a string uri for a node?!

Ok - i am very sorry confusing you - but maybe you giv some hints concerning given issues.
Thanks again!!

**Comment by luisgoncalves** [comment]
- a) I think XML canonicalization is meant to handle this (documents will still be equivalent)
- b) OK
- c) For the references that are added automatically, you can't change this. Anyway, as long as they are equivalent, this won't break the signature (xades4j adds canonicalization transform even if it is the default defined by XML-DSIG)
- d) Please read the docs: https://github.com/luisgoncalves/xades4j/wiki/DefiningQualifyingProperties#data-object-properties
- e) Change `getDigestAlgorithmForReferenceProperties` in `AlgorithmsProviderEx`
- f) I don't know what you're trying to accomplish. Do you know the XML-DSIG spec? (https://www.w3.org/TR/xmldsig-core1/#sec-URI)  The easiest way is probably to use a reference to the element o sign using its ID (`#<id>`). Check the tests in the lib for examples. If there isn't an ID, you can also build a xpath expression.

**Comment by luisgoncalves** [comment]
Did you manage to overcome the issues?
