### ISSUE TITLE
SigningCertificate property contains one or more certificates that are not part of the certification path.

### ISSUE THREAD

**Issue by fplou** [luisgoncalves/xades4j#195]
Hello Luis,
I am actually in the process to update xades4j in order to support last schema from ETSI.
During my tests, I encounter a problem I would need your opinion on it.
One of my test consist to sign a document with an enveloped xml signature. For this test I use a certificate signed by an authority (root one). I have created this certificate and this authority.

After the signature, in the KeyInfo I have the signing certificate:

        <ds:KeyInfo>
          <ds:X509Data>
            <ds:X509Certificate>...</ds:X509Certificate>
            <ds:X509IssuerSerial>
              <ds:X509IssuerName>cn=Valerian,ou=Valerian,o=Valerian S.A,l=Noisy Le Grand,st=Ile De France,c=FR</ds:X509IssuerName>
              <ds:X509SerialNumber>67890</ds:X509SerialNumber>
            </ds:X509IssuerSerial>
            <ds:X509SubjectName>cn=Georges\,Dupont,o=Elcimai Financial Software,l=Melun\, Nord,st=Ile de France,c=FR</ds:X509SubjectName>
          </ds:X509Data>
        </ds:KeyInfo>

In the xades:SigningCertificate tag I have the signing certificate reference and the authority reference :
 
                <xades:SigningCertificate>
                  <xades:Cert>
                    <xades:CertDigest>
                      <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                      <ds:DigestValue>aYnHk1BAJ+7hqe1xTlbQsO4lyHtb0Q5CJGO68FeFZMk=</ds:DigestValue>
                    </xades:CertDigest>
                    <xades:IssuerSerial>
                      <ds:X509IssuerName>cn=Valerian,ou=Valerian,o=Valerian S.A,l=Noisy Le Grand,st=Ile De France,c=FR</ds:X509IssuerName>
                      <ds:X509SerialNumber>67890</ds:X509SerialNumber>
                    </xades:IssuerSerial>
                  </xades:Cert>
                  <xades:Cert>
                    <xades:CertDigest>
                      <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                      <ds:DigestValue>kQcEAhtEGF1GdAfOMmPwxEhHSBkV+Xj0FzWKWT4L2ug=</ds:DigestValue>
                    </xades:CertDigest>
                    <xades:IssuerSerial>
                      <ds:X509IssuerName>cn=Valerian,ou=Valerian,o=Valerian S.A,l=Noisy Le Grand,st=Ile De France,c=FR</ds:X509IssuerName>
                      <ds:X509SerialNumber>14437758688125841206</ds:X509SerialNumber>
                    </xades:IssuerSerial>
                  </xades:Cert>
                </xades:SigningCertificate>

It seems ok for me. I generated the signature with the 1.5.1 release and my new release. It works the same.

During verification (with 1.5.1 and my new release), I got the following error message : 

SigningCertificate property contains one or more certificates that are not part of the certification path.
Stack trace with 1.5.1 release:

xades4j.verification.SigningCertificateCertsNotInCertPathException: Verification failed for property 'SigningCertificate': SigningCertificate property contains one or more certificates that are not part of the certification path.
	at xades4j.verification.SigningCertificateVerifier.verify(SigningCertificateVerifier.java:116)
	at xades4j.verification.SigningCertificateVerifier.verify(SigningCertificateVerifier.java:35)
	at xades4j.verification.QualifyingPropertiesVerifierImpl.verifyProperties(QualifyingPropertiesVerifierImpl.java:59)
	at xades4j.verification.XadesVerifierImpl.verify(XadesVerifierImpl.java:215)
	at fr.efs.ebam.validation.EbamSignatureVerify.validateXades(EbamSignatureVerify.java:374)
	at fr.efs.ebam.validation.EbamSignatureVerify.main(EbamSignatureVerify.java:1304)

In SigningCertificateVerifier method, the problem is located at this test : 

        // "Should this property contain one or more references to certificates
        // other than those present in the certification path, the verifier should
        // assume that a failure has occurred during the verification."
        if (nMatchedRefs < certRefs.size())
            throw new SigningCertificateCertsNotInCertPathException();

As certRefs contains two certificates (the signing certificate and the authority) and certPathIter only contains one reference (the signing certificate), it seems normal to get this error.  But I do not think it is the way it must work. What is your feeling. Do you think the problem is only located in SigningCertificateVerifier or do you think the problem is elsewhere?

Thanks for your help.

By the way, when the new release will be ready, I will share the code with you.

Regards.

Francois

**Comment by luisgoncalves** [comment]
Hello,

The code is implemented as stated in XAdEs 1.4.1 section G.2.2.5 (text quoted in the source code comments), so it cannot be changed.

`CertificateValidationProvider` (whose result is used to feed `QualifyingPropertyVerificationContext.getCertChainData()`) is supposed to return the full chain, including the trust root (check `ValidationData` docs). In that case, everything plays out. Are you sure that this is the case in your scenario?

**Comment by fplou** [comment]
Hello Luis,

The signing certificate was generated from a root authority.
SigningCertificate tag contains 2 references : the signing certificate and the root authority.

So we are in the following case according section G.2.2.5 :

If SigningCertificate contains references to other certificates in the path, the verifier should proceed to check each of the certificates in the certification path against them.

The getCertChainData only contains the signing certificate. This explain why the checking of root authority failed.

So two solutions : 

The certChainData is incomplete
The verification is not totally accurate

I will do more debugging to try to understand how the chainData is built.

Regards

Francois

**Comment by luisgoncalves** [comment]
I think that `SigningCertificateVerifier` is fine, given that:
1. I was actually referring to this part of G.2.2.5:
> Should this property contain one or more references to certificates other than those present in the certification path, the verifier should assume that a failure has occurred during the verification.
2. The `SigningCertificateVerifier` expects that `certChainData` includes the full certificate chain.

I don't know which `CertificateValidationProvider` you are using, but xades4j will get the certificate chain from it and supply it to the `QualifyingPropertyVerificationContext`.

**Comment by fplou** [comment]
I think problem is the difference between KeyInfo and SigningCertificate. The KeyInfo only contains one certificate (the signing one) and SigningCertificate contains the signing and the root authority.

I look to another xades sample file transmitted by one of my customer and the KeyInfo contains all chain certificates but SigningCertificate contains only the signing certificate. So the verification is working well in this case.

I think the problem is on signature process. I use the following code to sign :

    private static void signBes() throws Exception
    {
		DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
		dbf.setNamespaceAware(true);
		Document doc = dbf.newDocumentBuilder().parse(new File(DOCUMENT));

        Element elem = doc.getDocumentElement();
        DOMHelper.useIdAsXmlId(elem);
        

        KeyingDataProvider kdp = new FileSystemKeyStoreKeyingDataProvider(
                "pkcs12",
                CERT_FOLDER + CERT,
                new FirstCertificateSelector(),
                new DirectPasswordProvider(PASS),
                new DirectPasswordProvider(PASS),
                true);

        Node nodeToSign = elem.getFirstChild();
        DataObjectDesc obj = new EnvelopedXmlObject(nodeToSign,"text/xml",null);
        
        SignedDataObjects dataObjs = new SignedDataObjects().withSignedDataObject(obj);

        XadesSigner signer = new XadesBesSigningProfile(kdp).newSigner();
        signer.sign(dataObjs, elem.getElementsByTagName("Sgntr").item(0));	// elem : node to attach Signature
        
        TransformerFactory tFactory = TransformerFactory.newInstance();
        Transformer transformer = tFactory.newTransformer();
        DOMSource source = new DOMSource(doc);        
        StreamResult result = new StreamResult(new File(SIGNED));
        transformer.transform(source, result);
    }

**Comment by luisgoncalves** [comment]
During verification, xades4j tries to gather certificates from where possible, namely KeyInfo. The gathered certificates are supplied to `CertificateValidationProvider`. Any certificate that is needed to build the chain and is not present in the supplied list needs to be obtained by the `CertificateValidationProvider` itself.

This is why `PKIXCertificateValidationProvider` - one builtin implementation of `CertificateValidationProvider` - has an optional parameter to specify additional certificate stores.

So, even if your signing process doesn't include all the certificates in the signature itself, validation should be able to gather them. It depends on which `CertificateValidationProvider` you are using and how it is being configured.

That said, you can configure xades4j to include the full certificate chain in KeyInfo when available: https://github.com/luisgoncalves/xades4j/wiki/OtherSigningOptions#keyinfo-content.

**Comment by fplou** [comment]
Thanks for your help.

I modified the signing code in order to have the signing certificate and the root authority certificate in KeyInfo but the verification still failed for same reason :

        XadesBesSigningProfile profile = new XadesBesSigningProfile(kdp);
        BasicSignatureOptions sigopt = new BasicSignatureOptions();
        sigopt.includeSigningCertificate(SigningCertificateMode.FULL_CHAIN);
        profile.withBasicSignatureOptions(sigopt);
        XadesSigner signer = profile.newSigner();
        signer.sign(dataObjs, elem.getElementsByTagName("Sgntr").item(0));	// elem : node to attach Signature


So I added a certstore will all certificates and passed it to PKIXCertificateValidationProvider but again the same error message.

I have to investigate further.

Francois

**Comment by fplou** [comment]
Hello,
I found the problem. My trustAnchor was incorrect and the signing certificate was included in it. That's all ;-)

Thanks for your help.

Francois

**Comment by luisgoncalves** [comment]
Cool!
