### ISSUE TITLE
AlgorithmParametersMarshaller not available

### ISSUE THREAD

**Issue by fplou** [luisgoncalves/xades4j#197]
Hi,

I try to sign a XML file with a specific Transform :

DataObjectDesc obj = new EnvelopedXmlObject(nodeToSign,"text/xml",null).withTransform(new RemoveWhitespaceBetweenElementsTransform());

But during signing I received following exception : 

Exception in thread "main" xades4j.UnsupportedAlgorithmException: AlgorithmParametersMarshaller not available (urn:swift:transform:remove-whitespace-between-elements)
	at xades4j.xml.marshalling.algorithms.AlgorithmsParametersMarshallingProviderImpl.marshalParameters(AlgorithmsParametersMarshallingProviderImpl.java:55)
	at xades4j.utils.TransformUtils.createTransforms(TransformUtils.java:84)
	at xades4j.production.SignedDataObjectsProcessor.processTransforms(SignedDataObjectsProcessor.java:181)
	at xades4j.production.SignedDataObjectsProcessor.process(SignedDataObjectsProcessor.java:92)
	at xades4j.production.SignerBES.sign(SignerBES.java:183)
	at xades4j.production.SignerBES.sign(SignerBES.java:135)
	at testXades.testXades.signBes(testXades.java:121)
	at testXades.testXades.main(testXades.java:75)

I try to understand what I missed but I can not find.

Could you provide me with some guidance?

Thanks

Regards

François

**Comment by luisgoncalves** [comment]
Hi @fplou ,

You actually bumped into a flaw of the library. It allows you to extend `Algorithm` but there's not way to register a `AlgorithmParametersMarshaller` for it. In you scenario the transform probably doesn't even have parameters, which makes this even worse.

Can you try using the `GenericAlgorithm` class directly instead of extending it or `Algorithm`? That class has a built-in parameters marshaller.

**Comment by fplou** [comment]
Hi Luis,
It works with GenericAlgorithm and by registering my transformation before:

        org.apache.xml.security.transforms.Transform.register(RemoveWhitespaceBetweenElements2.TRANSFORM_URI, RemoveWhitespaceBetweenElements2.class);
        
DataObjectDesc obj = new EnvelopedXmlObject(nodeToSign,"text/xml",null).withTransform(new GenericAlgorithm(RemoveWhitespaceBetweenElements2.TRANSFORM_URI));

Thanks

François

**Comment by fplou** [comment]
Hi Luis,

I also need to use a transformation with a parameter. This transformation is an XSLT one.
To be short, the parameter is a simple value :  1 or 2 depending of the signatory.

I do not understand how to retrieve this parameter from the Transformation.
The transformation class extends TransformSpi.

Thanks for your help.

François

**Comment by fplou** [comment]
I found a solution (I do not like it but it works) by using System.setProperty.

Thanks

François

**Comment by luisgoncalves** [comment]
I'm glad you're able to configure it. Nevertheless, this highlights that adding a custom transform is not so easy... I'll think a bit about options; at least writing down something in the docs.

Regarding the XSLT with parameters, I didn't understand what you needed to do. Do you want to provide more details? (I must say that applying a XSLT during the signing process seems a bit weird...)

**Comment by luisgoncalves** [comment]
I think I now understood what you're asking. The parameter `Node`s should be children of the `Transform`. Check this example from Apache Santuario: https://apache.googlesource.com/santuario-java/+/refs/tags/xmlsec-2.0.7/src/main/java/org/apache/xml/security/transforms/implementations/TransformXPath2Filter.java

Also, keep in mind that Santuario also supports XSLT tranforms.
