### ISSUE TITLE
QualifyingPropertiesReference support is missing

### ISSUE THREAD

**Issue by CoreyDov** [luisgoncalves/xades4j#200]
It seems that there is no means to add the QualifyingPropertiesReference element for ds:Object. This is sometimes required for the validation of the signature, for example the URI can be used to locate a certificate.

**Comment by luisgoncalves** [comment]
Can you provide more details on the use-case?

**Comment by CoreyDov** [comment]
<QualifyingPropertiesReference xmlns="http://uri.etsi.org/01903/v1.3.2#" URI="**Location of certificate**"/>

The URI can be used to locate the certificate used to verify the signature

**Comment by luisgoncalves** [comment]
The URI property indicates the location of the referenced `QualifyingProperties`, not a specific certificate(s)...  In my opinion locating that certificate would be something that is provided by a verifying library as part of processing the `QualifyingProperties` (doesn't really matter if they are incorporated in the same XML resource or not).

Anyway, the complexity of adding support for distributed `QualifyingProperties` - specially for verification - doesn't seem to be worthy, so far.

**Comment by luisgoncalves** [comment]
I'm closing this, as the use case was not clear. If you have any additional comments, feel free to re-open.
