### ISSUE TITLE
Java version for xades4j

### ISSUE THREAD

**Issue by DanyelDes** [luisgoncalves/xades4j#201]
Which is the better version java for working xades4j ??

I have problems with Java 11.

**Comment by nekkiy** [comment]
Xades4j are built by JDK version 6

**Comment by luisgoncalves** [comment]
Source code was mostly written in Java 6 and the target bytecode format is still set to 1.6. Current builds and tests are running on 8, 9 and 11: https://travis-ci.org/luisgoncalves/xades4j.

Which problems are you facing?

**Comment by DanyelDes** [comment]
I had problem with jaxb, because Java 11 not include, then I downloaded it and work perfect. Since Java 9 not include jaxb.
Still presents warnings with guice for standar encapsulation Java 9,10,11 "An illegal reflective access opetarion has ocurred".
Thanks for your attention.
