### ISSUE TITLE
xades4j.XAdES4jXMLSigException: Cannot resolve element with ID

### ISSUE THREAD

**Issue by maxeingt** [luisgoncalves/xades4j#213]
Hi Luis,
I am working in signature a XML with Xades Bes but when I have tried to execute I have the follow issue:
xades4j.XAdES4jXMLSigException: Cannot resolve element with ID

This is my code that I have modified based on your examples:

    public String signature(String pathCert, String xmlContent, CaviumKey key) {
        FileInputStream is = null;
        CertificateFactory fact;
        X509Certificate cer;
        DocumentBuilderFactory dbf;
        InputSource iso;
        Document doc = null;
        String xmlFirmado = "";
        try {
            dbf = DocumentBuilderFactory.newInstance();
            dbf.setNamespaceAware(true);
            iso = new InputSource(new StringReader(xmlContent));
            doc = dbf.newDocumentBuilder().parse(iso);
            
            Element elem = (Element)doc.getDocumentElement();
            DOMHelper.useIdAsXmlId(elem);
            
            fact    = CertificateFactory.getInstance("X.509");
            is      = new FileInputStream (pathCert);
            cer     = (X509Certificate) fact.generateCertificate(is);
            KeyingDataProvider kdp = new DirectKeyingDataProvider(cer,(CaviumRSAPrivateKey)key);
     
            DataObjectDesc obj = new DataObjectReference("#"+elem.getAttribute("ID"))
                .withTransform(new EnvelopedSignatureTransform());
            SignedDataObjects dataObjs = new SignedDataObjects()
                                         .withSignedDataObject(obj);
            
            XadesSigner signer = new XadesBesSigningProfile(kdp).newSigner();
            signer.sign(dataObjs, elem);
                    
            xmlFirmado = this.generateXMLSigned(doc);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ManageSignXadesXML.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CertificateException | ParserConfigurationException 
                | SAXException | XAdES4jException | IOException ex) {
            Logger.getLogger(ManageSignXadesXML.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        return xmlFirmado;
    }

I have tried to use: 
DataObjectDesc obj = new DataObjectReference("");
and the code work but generate a signature invalid.

**Comment by luisgoncalves** [comment]
Hi,

Are you sure that the root element of the XML contained in `xmlContent` has an ID attribute? The exception message seems to indicate that it doesn't ("with ID" and then it seems that an empty string follows).

**Comment by maxeingt** [comment]
Hi, 

thank you for response me, this is the initial structure of the XML, the root element doesn't have ID attribute, the current XML already has a signature but I need add  a second signature, when I have tried to use DataObjectDesc obj = new DataObjectReference(""); the signature is generated invalid and corrupt the previous signature too. 
<?xml version="1.0"?>
<dte:GTDocumento Version="0.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:cno="http://www.sat.gob.gt/face2/ComplementoReferenciaNota/0.1.0" xmlns:cfe="http://www.sat.gob.gt/face2/ComplementoFacturaEspecial/0.1.0" xmlns:cex="http://www.sat.gob.gt/face2/ComplementoExportaciones/0.1.0" xmlns:cfc="http://www.sat.gob.gt/dte/fel/CompCambiaria/0.1.0" Id="#DatosCertificados" xmlns:dte="http://www.sat.gob.gt/dte/fel/0.2.0">
<dte:SAT ClaseDocumento="dte">
<dte:DTE ID="DatosCertificados">
<dte:DatosEmision ID="DatosEmision">

The other signature make reference to "DatosEmision" ID, below a initial structure of the previous signature
<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="Signature-56sasbb-9d96-4da8-9641-f0af9ba64175">
<ds:SignedInfo>
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
<ds:Reference Id="Reference-92543022-e118-46fb-91be-6a66a14bd100" URI="#DatosEmision">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>sykeni8UuzIV9eB791+1WESbxJ8Ib4t3eWgf5o=</ds:DigestValue>
</ds:Reference>

Thank you for your quickly response.

**Comment by luisgoncalves** [comment]
Ok, so there's your problem. I don't know exactly which element you need to sign, but use the ID of that one. IINM, the `EnvelopedSignatureTransform` will exclude the signature being generate from the signing process, but no others.

Adding a new signature shouldn't corrupt the existing one; maybe it's the parsing/writing of the xml that is causing that. Anyway, you probably don't want the second signature to cover the first because it will break if the first signature is updated (e.g. to include new unsigned properties).

**Comment by maxeingt** [comment]
Is correct, I am not interesed in the other signature, I am only add the new signature based on my private key and certificate, and attach it in the XML, below you can see the XML structure complete, but I am not sure what I need do to for sign it, you think that my problem is the parse and write? I should work in bytes[] instance of String for avoid the corruption?

<?xml version="1.0"?>
<dte:GTDocumento xmlns:dte="http://www.sat.gob.gt/dte/fel/0.2.0" Id="#DatosCertificados" xmlns:cfc="http://www.sat.gob.gt/dte/fel/CompCambiaria/0.1.0" xmlns:cex="http://www.sat.gob.gt/face2/ComplementoExportaciones/0.1.0" xmlns:cfe="http://www.sat.gob.gt/face2/ComplementoFacturaEspecial/0.1.0" xmlns:cno="http://www.sat.gob.gt/face2/ComplementoReferenciaNota/0.1.0" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="0.1">	<dte:SAT ClaseDocumento="dte">		<dte:DTE ID="DatosCertificados">			<dte:DatosEmision ID="DatosEmision">				<dte:DatosGenerales Tipo="FACT" FechaHoraEmision="2020-10-13T00:00:00-06:00" CodigoMoneda="GTQ"/>				<dte:Emisor NITEmisor="325239" NombreEmisor="Company" CodigoEstablecimiento="1" NombreComercial="Company" CorreoEmisor="" AfiliacionIVA="GEN">					<dte:DireccionEmisor>						<dte:Direccion>Direccion</dte:Direccion>						<dte:CodigoPostal>0</dte:CodigoPostal>						<dte:Municipio>Municipio</dte:Municipio>						<dte:Departamento>Departamento</dte:Departamento>						<dte:Pais>GT</dte:Pais>					</dte:DireccionEmisor>				</dte:Emisor>				<dte:Receptor IDReceptor="92623232" NombreReceptor="SOLUCIONES, S.A." CorreoReceptor="fel@soluciones.com">					<dte:DireccionReceptor>						<dte:Direccion>Direccion</dte:Direccion>						<dte:CodigoPostal>0</dte:CodigoPostal>						<dte:Municipio/>						<dte:Departamento/>						<dte:Pais>GT</dte:Pais>					</dte:DireccionReceptor>				</dte:Receptor><dte:Frases><dte:Frase TipoFrase="1" CodigoEscenario="1"/></dte:Frases>				<dte:Items><dte:Item NumeroLinea="1" BienOServicio="S">	<dte:Cantidad>232</dte:Cantidad>	<dte:Descripcion>Nuevo</dte:Descripcion>	<dte:PrecioUnitario>5</dte:PrecioUnitario>	<dte:Precio>5</dte:Precio>	<dte:Descuento>0.00000</dte:Descuento>	<dte:Impuestos>		<dte:Impuesto>			<dte:NombreCorto>IVA</dte:NombreCorto>			<dte:CodigoUnidadGravable>1</dte:CodigoUnidadGravable>			<dte:MontoGravable>49</dte:MontoGravable>			<dte:MontoImpuesto>53</dte:MontoImpuesto>		</dte:Impuesto>	</dte:Impuestos>	<dte:Total>5</dte:Total></dte:Item>				</dte:Items>				<dte:Totales><dte:TotalImpuestos>	<dte:TotalImpuesto NombreCorto="IVA" TotalMontoImpuesto="53"/></dte:TotalImpuestos>					<dte:GranTotal>52</dte:GranTotal>				</dte:Totales>			</dte:DatosEmision><dte:Certificacion><dte:NITCertificador>23234</dte:NITCertificador><dte:NombreCertificador>Superintendencia de Administracion Tributaria</dte:NombreCertificador><dte:NumeroAutorizacion Numero="202342" Serie="E45CBC88">E43432</dte:NumeroAutorizacion><dte:FechaHoraCertificacion>2020-10-07T12:38:25-06:00</dte:FechaHoraCertificacion></dte:Certificacion></dte:DTE>	</dte:SAT><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="Signature-56cab2bb-9d96-4da8-9641-f0af9ba6sdfs5"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/><ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/><ds:Reference Id="Reference-92543022-e118-46fb-91be-6a66a14bd100" URI="#DatosEmision"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ds:DigestValue>sykeni8UuzIV9eB791+1WESbxJ8Ib4t3eWdfsdf=</ds:DigestValue></ds:Reference><ds:Reference Id="ReferenceKeyInfo" URI="#KeyInfoId-Signature-56cab2bb-9d96-4da8-9641-f0"><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ds:DigestValue>rHsTHVzyoZKER63QZ=</ds:DigestValue></ds:Reference><ds:Reference Type="http://uri.etsi.org/01903#SignedProperties" URI="#SignedProperties-Signature-56cab2bb-9d96-4da8-9641-f0af9ba64175"><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ds:DigestValue>PtCpZYQ=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue Id="SignatureValue-56cab2bb-9d96-4da8-9641-f0af9ba64175">tCpv4Eowk8jQoJSCacf7VffE2zF0r4h2a0UzP/Yl4OJb1+kCLERFT+qEJc/jpLcS8ffAQVC79MWzfoPxIRjQMgOzz2wrHiOwZ26ZsWYGdwJ7A==</ds:SignatureValue><ds:KeyInfo Id="KeyInfoId-Signature-56cab2bb-9d96-4da8-9641-f0af9ba64175"><ds:X509Data><ds:X509Certificate>sdf=</ds:X509Certificate></ds:X509Data><ds:KeyValue><ds:RSAKeyValue><ds:Modulus>r4ZbKNa==</ds:Modulus><ds:Exponent>AQAB</ds:Exponent></ds:RSAKeyValue></ds:KeyValue></ds:KeyInfo><ds:Object Id="XadesObjectId-a557574f-4227-49ac-b0b4-0a0885d332e7"><xades:QualifyingProperties xmlns:xades="http://uri.etsi.org/01903/v1.3.2#" Id="QualifyingProperties-426a0fa6-29a3-47a7-a656-5d1126afcfab" Target="#Signature-56cab2bb-9d96-4da8-9641-f0af9ba64175"><xades:SignedProperties Id="SignedProperties-Signature-56cab2bb-9d96-4da8-9641-f0af9ba64175"><xades:SignedSignatureProperties><xades:SigningTime>2020-10-13T12:38:21-06:00</xades:SigningTime><xades:SigningCertificate><xades:Cert><xades:CertDigest><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ds:DigestValue>P0/+x3RLpho5aDgsFdxIPNmKw8m9FGhj8ia9/iJaDlc=</ds:DigestValue></xades:CertDigest><xades:IssuerSerial><ds:X509IssuerName>CN=SAT-TEST-CA</ds:X509IssuerName><ds:X509SerialNumber>8765575883380140837</ds:X509SerialNumber></xades:IssuerSerial></xades:Cert></xades:SigningCertificate></xades:SignedSignatureProperties><xades:SignedDataObjectProperties><xades:DataObjectFormat ObjectReference="#Reference-92543022-e118-46fb-91be-6a6d100"><xades:MimeType>text/xml</xades:MimeType><xades:Encoding>UTF-8</xades:Encoding></xades:DataObjectFormat></xades:SignedDataObjectProperties></xades:SignedProperties></xades:QualifyingProperties></ds:Object></ds:Signature></dte:GTDocumento>

**Comment by maxeingt** [comment]
I have tested parsing the data to byte[] and return byte[] too, using DataObjectDesc obj = new DataObjectReference("");
but continue generate a invalid signature

![imagen](https://user-images.githubusercontent.com/18448595/100474946-6f4e3480-30a7-11eb-9145-e5502f573dbc.png)

**Comment by luisgoncalves** [comment]
I mentioned parsing/writing because I've seen other people doing a lot of string/encoding mangling that messed up the xml file. If you are reading from a file you may as well read from the file directly instead of a string.

Regarding your issues, try starting with an isolated document (or one without another signature) to see if everything else is correct. I don't know how the verification is being done...

Anyway, this doesn't seem like a problem with the xades4j library. I'm not sure I can help you much more.

**Comment by maxeingt** [comment]
Thank you

**Comment by maxeingt** [comment]
Hi Luis,

thank you, I have resolved my issue using XPath and using the correct section in the reference, thank you.

Regards

**Comment by kurbhatt** [comment]
Hello @maxeingt.
Can you please share code snippet in which XPath has been used?

**Comment by maxeingt** [comment]
Hi @kurbhatt 

sorry, this is the code that I have used

protected Element getElementToSign(Document doc){
    
        Element elem = null;
        elem         = (Element)doc.getDocumentElement();
        
        try {
            
            Element elem1 = this.getIDBasedOnTypeDoc(doc);

            elem1.setAttributeNS(null, "ID", this.getTagID());
            
            elem1.setIdAttributeNode(elem1.getAttributeNode("ID"), true);

        } catch (XPathExpressionException ex) {
            Logger.getLogger(ManageSignJXadesXML.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return elem;
        
    }

    private Element getIDBasedOnTypeDoc(Document doc) throws XPathExpressionException{
            
            XPath xPath = XPathFactory.newInstance().newXPath();
            xPath.setNamespaceContext(new NamespaceResolver(doc));
            
            String expression = "/dte:GTDocumento/dte:SAT/dte:DTE/dte:"
                                + "DatosEmision[@ID='DatosEmision']";
            
            NodeList nl = (NodeList) xPath.compile(expression)
                                    .evaluate(doc, XPathConstants.NODESET);
            
            if( nl.getLength() == 0 ) {
                tagID = "DatosCertificados";
                expression = "/dte:GTAnulacionDocumento/dte:SAT/"
                             + "dte:AnulacionDTE[@ID='DatosCertificados']";
                
                nl = (NodeList) xPath.compile(expression)
                                    .evaluate(doc, XPathConstants.NODESET);
            }
            
            return (Element)nl.item(0);
    }
