### ISSUE TITLE
Sign with pattern XADES-T not working

### ISSUE THREAD

**Issue by rcarauta** [luisgoncalves/xades4j#218]
I try to sign xml in pattern XADES-T. I use the xades4j version 1.4.0 because the version 1.6.0 not working and shwo this error for sign. 
`1) Error injecting constructor, java.lang.NoSuchFieldError: defaultLookUp
  at xades4j.providers.impl.DefaultX500NameStyleProvider.<init>(DefaultX500NameStyleProvider.java:22)
  while locating xades4j.providers.impl.DefaultX500NameStyleProvider
  while locating xades4j.providers.X500NameStyleProvider
    for parameter 10 at xades4j.production.SignerBES.<init>(SignerBES.java:101)
  while locating xades4j.production.SignerBES

1 error] with root cause`

In version 1.4.0 sign with this code works:

`DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
		DocumentBuilder builder = factory.newDocumentBuilder();
		Document doc = builder.parse(new InputSource(new StringReader(readFile.readFile(file))));		
        Element elem = doc.getDocumentElement();
        KeyingDataProvider kdp = new FileSystemKeyStoreKeyingDataProvider(
                "pkcs12",
                certificado,
                new FirstCertificateSelector(),
                new DirectPasswordProvider(password),
                new DirectPasswordProvider(password),
                true);      
        elem.setIdAttribute("ID", true);
        DataObjectDesc obj = new DataObjectReference("#" + elem.getAttribute("ID"))
                .withTransform(new EnvelopedSignatureTransform());
        SignedDataObjects dataObjs = new SignedDataObjects().withSignedDataObject(obj);
        XadesSigner signer = new XadesBesSigningProfile(kdp).newSigner();
        signer.sign(dataObjs, elem);
        TransformerFactory tFactory = TransformerFactory.newInstance();
        Transformer transformer = tFactory.newTransformer();
        DOMSource source = new DOMSource(doc);
        File fileSign = new File(SIGNED+numero+".xml");
        StreamResult result = new StreamResult(fileSign);
        transformer.transform(source, result);`

But when I try to change for pattern XADES-T is not working:

`DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
		DocumentBuilder builder = factory.newDocumentBuilder();
		Document doc = builder.parse(new InputSource(new StringReader(readFile.readFile(file))));		
        Element elem = doc.getDocumentElement();
        KeyingDataProvider kdp = new FileSystemKeyStoreKeyingDataProvider(
                "pkcs12",
                certificado,
                new FirstCertificateSelector(),
                new DirectPasswordProvider(password),
                new DirectPasswordProvider(password),
                true);      
        elem.setIdAttribute("ID", true);
        DataObjectDesc obj = new DataObjectReference("#" + elem.getAttribute("ID"))
                .withTransform(new EnvelopedSignatureTransform());
        SignedDataObjects dataObjs = new SignedDataObjects().withSignedDataObject(obj);
        XadesSigner signer = new XadesTSigningProfile(kdp).newSigner();
        signer.sign(dataObjs, elem);
        TransformerFactory tFactory = TransformerFactory.newInstance();
        Transformer transformer = tFactory.newTransformer();
        DOMSource source = new DOMSource(doc);
        File fileSign = new File(SIGNED+numero+".xml");
        StreamResult result = new StreamResult(fileSign);
        transformer.transform(source, result);`

The error when I try to sign with this code is: 

`2021-02-14 18:36:40.312[0;39m [31mERROR[0;39m [35m14184[0;39m [2m---[0;39m [2m[nio-8080-exec-1][0;39m [36mo.a.c.c.C.[.[.[/].[dispatcherServlet]   [0;39m [2m:[0;39m Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchFieldError: gostR3411] with root cause

java.lang.NoSuchFieldError: gostR3411
	at org.bouncycastle.tsp.TSPAlgorithms.<clinit>(Unknown Source) ~[bcpkix-jdk15on-1.50.jar:1.50.0]
	at xades4j.providers.impl.AbstractTimeStampTokenProvider.<clinit>(AbstractTimeStampTokenProvider.java:47) ~[xades4j-1.4.0.jar:na]
	at xades4j.providers.impl.HttpTimeStampTokenProvider$$FastClassByGuice$$2830898f.newInstance(<generated>) ~[guice-2.0.jar:na]`

I don't know why this is happend and how I solve this error.

**Comment by luisgoncalves** [comment]
Which version of Bouncy Castle do you have installed in your project? The errors seem to indicate some mismatch there. Maybe BC introduced some breaking change.. xades4j [currently depends on 1.56](https://github.com/luisgoncalves/xades4j/blob/master/pom.xml#L17).

**Comment by rcarauta** [comment]
I try to use this version 1.56. Let me explain. I use zades4j solution in my project and I import in pom.xml these dependencies. I show my project and the dependency here. I think has an error in sign with the XADES-T pattern. my pom.xml and my project is in this link. [pom.xml](https://github.com/rcarauta/xades_pattern/blob/master/pom.xml). In here you can see all packages and dependencies in project.

**Comment by luisgoncalves** [comment]
You have another dependency to Bouncy Castle in your POM:

```
		<dependency>
			<groupId>org.bouncycastle</groupId>
			<artifactId>bcprov-jdk16</artifactId>
			<version>1.46</version>
		</dependency>
```

This is probably conflicting with the other one, further down:

```
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>${bouncycastle.version}</version>
        </dependency>
```

Please close the ticket if this solves your problem.

**Comment by luisgoncalves** [comment]
Did you solve the issue?

**Comment by rcarauta** [comment]
Yes. This change solve the issue in version 1.4.1. Now it's sign correctl. Thanks for your help. This project is very good ofr sign documents.
