### ISSUE TITLE
It seems Xades-Bes signing doesn't work

### ISSUE THREAD

**Issue by piotrkot** [luisgoncalves/xades4j#220]
I have this simple XML document which I sign with:
```
final Document xml = DocumentBuilderFactory
            .newInstance()
            .newDocumentBuilder()
            .parse(doc);
        final Element elem = xml.getDocumentElement();
        elem.setAttribute("Id", "Root");
        DOMHelper.useIdAsXmlId(elem);
        final KeyingDataProvider kdp = new FileSystemKeyStoreKeyingDataProvider(
            "pkcs12",
            path.toString(),
            list -> list.get(0),
            () -> storepass,
            (str, cert) -> entrypass,
            true
        );
        final DataObjectDesc obj = new DataObjectReference("#Root")
            .withTransform(new EnvelopedSignatureTransform());
        final SignedDataObjects signature = new SignedDataObjects()
            .withSignedDataObject(obj);
        final XadesSigner signer = new XadesBesSigningProfile(kdp).newSigner();
        signer.sign(signature, elem);
        final TransformerFactory factory = TransformerFactory.newInstance();
        final Transformer transformer = factory.newTransformer();
        final DOMSource source = new DOMSource(xml);
        final TempFile tmp = new TempFile();
        final StreamResult result = new StreamResult(tmp.value().toFile());
        transformer.transform(source, result);
```
As a result I get a signed XML document. However, external tools used for verification say that:

`The signature was verified negatively - Invalid hash in the Reference object in XML signature.-#Root`

Is there a problem with the library (version 1.6.0) or I use it improperly?

**Comment by luisgoncalves** [comment]
At first glance your code looks correct. Have you tried verifying other xades4j signatures in that external tool? (e.g. signatures present on the tests). Have you tried previous versions of xades4j? There are no recent reports of similar issues..

**Comment by piotrkot** [comment]
I just tried `document.signed.bes.xml`, `document.signed.t.bes.xml`, and `document.signed.bes.cs.xml` from `src/test/xml/` directory and they are correctly verified by the external tool.
There could be a problem with my XML document. Attached is the signed XML document generated by the algorithm from the issue description.
[xml-signed.zip](https://github.com/luisgoncalves/xades4j/files/6017702/xml-signed.zip)
Do you think there can be anything special with this XML that makes the problem?

**Comment by piotrkot** [comment]
I will try some previous versions of xades4j.

**Comment by piotrkot** [comment]
I was still experimenting with version 1.6.0.
It turns out that signed XML
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<InitUpload>
    <DocumentType>JPK</DocumentType>
</InitUpload>
```
has signature verified positively by the external tool, while signed XML
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<InitUpload xmlns:e="http://e-dokumenty.mf.gov.pl">
    <e:DocumentType>JPK</e:DocumentType>
</InitUpload>
```
has signature verified negatively.
I think this is a bug in the library. @luisgoncalves don't you agree?

**Comment by piotrkot** [comment]
The same issue is observed with versions 1.5.1 and 1.5.0 of the xades4j.

**Comment by luisgoncalves** [comment]
Ah, namespaces. You probably need to use `setNamespaceAware` in your document builder factory. Can you try that?

**Comment by piotrkot** [comment]
Thank you. It solved the problem.
