### ISSUE TITLE
Xades-Bes interferes with document schema

### ISSUE THREAD

**Issue by piotrkot** [luisgoncalves/xades4j#221]
Xades4J adds `Id` attribute to the root element of the XML document it signs.
However, when XML document have XML schema constraints where `Id` element in root is not allowed, signed document becomes invalid (according to the XML schema).
Is adding `Id` attribute essential?

I should probably check the https://www.w3.org/TR/XAdES/ but it's really big.

**Comment by luisgoncalves** [comment]
Where exactly does xades4j add the `Id` attribute?

**Comment by piotrkot** [comment]
Let me refer to the implementation used in #220:
```
        final DocumentBuilderFactory docfactory = DocumentBuilderFactory
            .newInstance();
        docfactory.setNamespaceAware(true);
        final Document xml = docfactory.newDocumentBuilder()
            .parse(doc.content().stream());
        final Element elem = xml.getDocumentElement();
        elem.setAttribute("Id", "Root");
        DOMHelper.useIdAsXmlId(elem);
        final KeyingDataProvider kdp = new FileSystemKeyStoreKeyingDataProvider(
            "pkcs12",
            this.path.toString(),
            list -> list.get(0),
            () -> this.storepass,
            (str, cert) -> this.entrypass,
            true
        );
        final DataObjectDesc obj = new DataObjectReference("#Root")
            .withTransform(new EnvelopedSignatureTransform());
        final SignedDataObjects signature = new SignedDataObjects()
            .withSignedDataObject(obj);
        final XadesSigner signer = new XadesBesSigningProfile(kdp).newSigner();
        signer.sign(signature, elem);
        final TransformerFactory factory = TransformerFactory.newInstance();
        final Transformer transformer = factory.newTransformer();
        final DOMSource source = new DOMSource(xml);
        final TempFile tmp = new TempFile();
        final StreamResult result = new StreamResult(tmp.value().toFile());
        transformer.transform(source, result);
```
You're right. xades4j doesn't add the `Id` attribute. However, as far as I understand the `Id` attribute of the XML must be passed to the `DataObjectReference`. When XML document doesn't have the `Id` attribute I am forced to add it.[](url)

**Comment by piotrkot** [comment]
Oh, I see. Based on the [SO answer](https://stackoverflow.com/questions/29843071/xmldsig-do-i-have-to-specify-reference-uri-in-an-enveloped-signature)
the `Id` is not essential. One can call `new DataObjectReference("")` which according to the specs refers to the whole document.

**Comment by luisgoncalves** [comment]
You can also use transforms over the data object reference to add a XPath, for example.
