### ISSUE TITLE
Is there a support for ECDSA?

### ISSUE THREAD

**Issue by mohammad0022** [luisgoncalves/xades4j#225]
Can I use EC certificate to generate signature ?

**Comment by luisgoncalves** [comment]
In theory yes, as the underlying version of Apache Santuario should support EC. There aren't any tests covering this yet, though.

Anyway - assuming [this SO question](https://stackoverflow.com/questions/67402415/can-i-use-ecdsa-certificate-to-generate-signature-with-xades4j) was also posted by yourself - you're just hitting a limitation of the [default algorithms provider](https://github.com/luisgoncalves/xades4j/blob/master/src/main/java/xades4j/providers/impl/DefaultAlgorithmsProviderEx.java#L45).

You should [define your own algorithms provider](https://github.com/luisgoncalves/xades4j/wiki/ChangingAlgorithms) and configure it in the signing profile (`XadesSigningProfile.withAlgorithmsProviderEx()`).

Let me know if it works. I'll also try to find some time to add a test covering this scenario.

**Comment by mohammad0022** [comment]
Thanks @luisgoncalves for your response.
I included the EC within the [default algorithms provider](https://github.com/luisgoncalves/xades4j/blob/master/src/main/java/xades4j/providers/impl/DefaultAlgorithmsProviderEx.java#L45) and it worked fine.

static
{
    signatureAlgsMaps = new HashMap<String, Algorithm>(2);
    signatureAlgsMaps.put("DSA", new GenericAlgorithm(XMLSignature.ALGO_ID_SIGNATURE_DSA));
    signatureAlgsMaps.put("RSA", new GenericAlgorithm(XMLSignature.ALGO_ID_SIGNATURE_RSA_SHA256));
    **signatureAlgsMaps.put("EC", new GenericAlgorithm(XMLSignature.ALGO_ID_SIGNATURE_ECDSA_SHA256));**
}

Now I can sign with EC certificates.

**Comment by luisgoncalves** [comment]
Great.
My suggestion was more towards not changing the library source code, but that also works.

I'll keep this issue open until I improve this in the library code and add a test.
