### ISSUE TITLE
Xades4j - How can I enter a hash for SHA256?

### ISSUE THREAD

**Issue by nurvasi** [luisgoncalves/xades4j#234]
I need to sign xml files with XAdES-EPES enveloped, RSA-SHA256 with this hash: Quzn98x3PMbSHwbUzaj5f5KOpiH0u8bvmwbbbNkO9Es

I use this for the policy:

// politica
    SignaturePolicyInfoProvider policyInfoProvider = new SignaturePolicyInfoProvider() {
        @Override
        public SignaturePolicyBase getSignaturePolicy() {
            return new SignaturePolicyIdentifierProperty(

                    new ObjectIdentifier(
                            "https://www.batuz.eus/fitxategiak/batuz/ticketbai/sinadura_elektronikoaren_zehaztapenak_especificaciones_de_la_firma_electronica_v1_0.pdf",
                            IdentifierType.URI, ""),
                    new ByteArrayInputStream(
                            "https://www.batuz.eus/fitxategiak/batuz/ticketbai/sinadura_elektronikoaren_zehaztapenak_especificaciones_de_la_firma_electronica_v1_0.pdf"
                                    .getBytes())

            );
        }
    };

But it is not valid... Can anyone help me?? 
Thanks in advance

**Comment by luisgoncalves** [comment]
I don't fully understand your question. What isn't valid? The policy qualifying property? You're getting the bytes of the URL string of the policy. Should it be the bytes of the policy document instead?

**Comment by nurvasi** [comment]
This file is one example signed ok (an example not signed by me): 
Ejemplo_TicketBAI_B00000034_B2022_0101.xml

And this is the one I get with my program: Factura_firmada_Pruebas.xml
And it is not valid....

I have to sign with :

- Xades-EPES (Enveloped)
- RSA-SHA256 with this hash: Quzn98x3PMbSHwbUzaj5f5KOpiH0u8bvmwbbbNkO9Es=

But I don't know how do it with your library... can you help me??
Thank you for your atention

**Comment by nurvasi** [comment]
[Ficheros_Pruebas.zip](https://github.com/luisgoncalves/xades4j/files/6677459/Ficheros_Pruebas.zip)

Sorry, here are the files...

**Comment by luisgoncalves** [comment]
The digest value of the policy (inside `SignaturePolicyIdentifier`) is different. As I mentioned above, that's probably because you need to supply the bytes of the policy file.  Note that on you're code you're getting the bytes of a string containing the policy URL:

`"https://www.batuz.eus/fitxategiak/batuz/ticketbai/sinadura_elektronikoaren_zehaztapenak_especificaciones_de_la_firma_electronica_v1_0.pdf"
                                .getBytes()`

Instead, get the bytes of the actual file (e.g. download it and read it there).

Also, you seem to be missing the `DataObjectFormat` property. You can add it when defining the signed data objects. Perhaps I can provide more help if you show that part of the code.

**Comment by nurvasi** [comment]
Yes, of course!! here is my code
Really, thank you so much!!

[Firma.zip](https://github.com/luisgoncalves/xades4j/files/6677596/Firma.zip)

**Comment by luisgoncalves** [comment]
Some quick notes. But please read the docs instead of just copying the code from the tests or so.

- Set the `DocumentBuilderFactory` to eb namespace aware; not having that may cause issues.
- Change the parameter of `SignaturePolicyIdentifierProperty` so that you pass the InputStream of the **contents** of the policy file (not the URL where the file can be found).
- Instead of directly using `Enveloped`, define the stuff to sign using something like:
```
 DataObjectDesc ref = new DataObjectReference("")
   .withTransform(new EnvelopedSignatureTransform())
   // add other properties via the appropriate methods here
signer.sign(new SignedDataObjects(ref), elem);
```

**Comment by nurvasi** [comment]
Thank you Luis, 

I have been working with your library for days, I have read the wiki, but it is very difficult for me understand..., I have never worked with an electronic signature. 

I find it very difficult to understand  :-(

I will try work in your notes (for now I don't understand them much)

Thank you again

**Comment by luisgoncalves** [comment]
Perhaps skimming through the XML-DSIG and/or XAdES specs may help. My notes should directly map to changes in the code you sent me.

**Comment by nurvasi** [comment]
The second point is done, I think so:

`        byte[] policy_bytes = Files.readAllBytes(Paths.get(POLICY_DOCUMENT));
        
        SignaturePolicyInfoProvider policyInfoProvider = new SignaturePolicyInfoProvider()
        {
           
            public SignaturePolicyBase getSignaturePolicy()
            {
                return new SignaturePolicyIdentifierProperty(
                        new ObjectIdentifier("https://www.batuz.eus/fitxategiak/batuz/ticketbai/sinadura_elektronikoaren_zehaztapenak_especificaciones_de_la_firma_electronica_v1_0.pdf"),
                        policy_bytes)
                    .withLocationUrl("https://www.batuz.eus/fitxategiak/batuz/ticketbai/sinadura_elektronikoaren_zehaztapenak_especificaciones_de_la_firma_electronica_v1_0.pdf");
            }
        };      `

And I can see the correct HASH in the signed XML, but it is not valid yet... why???


[Factura_firmada_Pruebas.xml.txt](https://github.com/luisgoncalves/xades4j/files/6678093/Factura_firmada_Pruebas.xml.txt)

**Comment by luisgoncalves** [comment]
> And I can see the correct HASH in the signed XML

You mean the policy hash in `SignaturePolicyIdentifier`? Cool

Did you use `setNamespaceAware()` in the `DocumentBuilderFactory` ?  Doesn't the validation system provide any validation report...?

**Comment by luisgoncalves** [comment]
You are still missing the data object format property (when compared to the other example). Does the validating system require that?

**Comment by nurvasi** [comment]
> > And I can see the correct HASH in the signed XML
> 
> You mean the policy hash in `SignaturePolicyIdentifier`? Cool
> 
> Did you use `setNamespaceAware()` in the `DocumentBuilderFactory` ? Doesn't the validation system provide any validation report...?

I use a Spanish government program to validate the sign called "Autofirma" in which you can View signatures, and it only tells me that it is not valid. I don't know any other way ...
![Firma_no_valida](https://user-images.githubusercontent.com/11974551/122590881-71d3a400-d062-11eb-9f90-e88380ee7c14.jpg)


> You are still missing the data object format property (when compared to the other example). Does the validating system require that?

and sorry, where is it??


All this is because the Basque government obliges to implement a TICKETBAI standard, where each invoice must be sent in that signed XML format. The signature specifications are those of this document (The same document as before):

https://www.batuz.eus/fitxategiak/batuz/ticketbai/sinadura_elektronikoaren_zehaztapenak_especificaciones_de_la_firma_electronica_v1_0.pdf

I understand:
─   XAdESenveloped
─  RSA-based algorithm supported in ETSI TS 119 312 V1.3.1. As a minimum it is required: 

- Key size will be strictly greater than 1024.
- SHA256 or higher versions. 

The example xml is provided by them...

**Comment by luisgoncalves** [comment]
- The XML document uses a namespace prefix. Be sure to configure the `DocumentBuilderFactory` as I mentioned above.
- Search for `DataObjectFormat` in the example signature (from the policy XML it doesn't seem required, though).

I'm not sure how I can help you more... At a first glance you seem to be on the right track.

**Comment by nurvasi** [comment]
Again, THANK YOU Luis!!

**Comment by nurvasi** [comment]
You were rigth Luis, by changing ` DocumentBuilderFactory` as follows it is valid now! 

`DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();`
`dbf.setNamespaceAware(true);`
`DocumentBuilder db = dbf.newDocumentBuilder();`
`Document doc = db.parse(new File(DOCUMENT));``

THANK YOU!!

**Comment by luisgoncalves** [comment]
Great!

Reopen the ticket if any other issue arises.
