### ISSUE TITLE
Error generating signature with .pfx certificate DIAN Colombia

### ISSUE THREAD

**Issue by YordyHz** [luisgoncalves/xades4j#241]
Hello, I have reviewed the library and different implementations made for the electronic invoicing of DIAN Colombia (exmp: Issue #134 ) but I still get an error when generating the signature for the XML document.

When verifying the generated signature I get the following:
Signature is Invalid
Number of Reference Digests = 2
Reference 1 digest is invalid because the computed digest differs from the digest in the XML.
Reference 2 digest is invalid because the computed digest differs from the digest in the XML.

The code used to sign is as follows: 
`

public class Signer {

    private XadesSigner signer;
    private static final String POLICY_URL = "https://facturaelectronica.dian.gov.co/politicadefirma/v2/politicadefirmav2.pdf";

    private void initialize(String keyPath, String password) throws KeyStoreException, XadesProfileResolutionException {

        SignaturePolicyInfoProvider policyInfoProvider = new SignaturePolicyInfoProvider() {
            public SignaturePolicyBase getSignaturePolicy() {
                try {
                    return new SignaturePolicyIdentifierProperty(new ObjectIdentifier(POLICY_URL), new URL(POLICY_URL).openStream());
                } catch (MalformedURLException ex) {
                    return new SignaturePolicyImpliedProperty();
                } catch (IOException ex) {
                    return new SignaturePolicyImpliedProperty();
                }
            }
        };

        KeyingDataProvider kp = new FileSystemKeyStoreKeyingDataProvider(
                "pkcs12",
                keyPath,
                new FirstCertificateSelector(),
                new DirectPasswordProvider(password),
                new DirectPasswordProvider(password),
                false
        );

        XadesSigningProfile p = new XadesEpesSigningProfile(kp, policyInfoProvider);
        signer = p.newSigner();
    }

    private Node selectNode(Document doc) {
        NodeList tag = doc.getElementsByTagName("ext:ExtensionContent");
        return tag.item(0);
    }

    private DataObjectDesc createDataObjectToSign() {
        return new DataObjectReference("").withTransform(new EnvelopedSignatureTransform());
    }

    private void sign(DataObjectDesc dataObjRef, Node elemToSign) throws XAdES4jException {

        signer.sign(new SignedDataObjects(dataObjRef), elemToSign, SignatureAppendingStrategies.AsFirstChild);
    }

    public Document sign(Document doc, String keyPath, String password) throws KeyStoreException, ParserConfigurationException, SAXException, IOException, TransformerException, XAdES4jException {

        initialize(keyPath, password);
        Node elemToSign = selectNode(doc);
        DataObjectDesc DataObjectRef = createDataObjectToSign();
        sign(DataObjectRef, elemToSign);
        return doc;
    }
}

`

The signature I get:
[signature.txt](https://github.com/luisgoncalves/xades4j/files/7670393/signature.txt)

**Comment by luisgoncalves** [comment]
How did you create `doc`? Namely, if creating from a `DocumentBuilderFactory`, is it set to be namespace aware?

**Comment by YordyHz** [comment]
The code to create the document is as follows:

`
                DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
                dbf.setNamespaceAware(true);
                DocumentBuilder dbx = dbf.newDocumentBuilder();
                Document doc = dbx.newDocument();

`

And the code to save the file:

`
           File docXMLFile = new File(BASE + path + nameFile);
            TransformerFactory transformerFactory = TransformerFactory.newInstance();
            Transformer transformer = transformerFactory.newTransformer();
            DOMSource domSource = new DOMSource(doc);
            StreamResult streamResult = new StreamResult(docXMLFile);

            transformer.transform(domSource, streamResult);

`

**Comment by YordyHz** [comment]
> El código para crear el documento es el siguiente:
> 
> ```
> DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
> dbf.setNamespaceAware(true);
> DocumentBuilder dbx = dbf.newDocumentBuilder();
> Document doc = dbx.newDocument(); 
> 
> 
> //And the code to save the file:
> 
> File docXMLFile = new File(BASE + path + nameFile);
> TransformerFactory transformerFactory = TransformerFactory.newInstance();
> Transformer transformer = transformerFactory.newTransformer();
> DOMSource domSource = new DOMSource(doc);
> StreamResult streamResult = new StreamResult(docXMLFile);
> 
> transformer.transform(domSource, streamResult); 
> ```

The libraries used for this:

```
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
```

**Comment by luisgoncalves** [comment]
The XML file that you attached doesn't have the namespace declarations for `ds` and `xades` (e.g. `xmlns:ds="http://www.w3.org/2000/09/xmldsig#"`). Could anything else be mangling it?

**Comment by YordyHz** [comment]
> The XML file that you attached doesn't have the namespace declarations for `ds` and `xades` (e.g. `xmlns:ds="http://www.w3.org/2000/09/xmldsig#"`). Could anything else be mangling it?

The code to generate the signature is exactly the one shown in the first comment, and there is nothing additional that modifies the document. I don't know if the problem is the certificate itself or if the library has conflicts with .pfx signatures.

Used bookstores: 
```
<dependency>
            <groupId>org.apache.santuario</groupId>
            <artifactId>xmlsec</artifactId>
            <version>2.2.3</version>
        </dependency>
        
        <dependency>
            <groupId>com.googlecode.xades4j</groupId>
            <artifactId>xades4j</artifactId>
            <version>1.7.0</version>
            <type>jar</type>
        </dependency>
```

The exact generated file is as follows:
[nie08920994992100000001.txt](https://github.com/luisgoncalves/xades4j/files/7686142/nie08920994992100000001.txt)

**Comment by luisgoncalves** [comment]
The signature looks good at first glance. What do you mean by "certificate itself or if the library has conflicts with .pfx signatures"? The errors you're getting are clear about the failure: the `Reference` digests don't match the values calculated by the verifier; this means that the inputs changed somehow.

Can you try writing code to verify it also with xades4j? If it also fails, then there must be something changing the file/document/output.

**Comment by luisgoncalves** [comment]
@YordyHz any news on this issue?

**Comment by YordyHz** [comment]
I made some changes in the process, previously the document was created and signed in the same process before saving, now it is saved without signing, then the file is called and signed, with this a different response was obtained when validating the firm ([Validator](https://tools.chilkat.io/xmlDsigVerify.cshtml))

```
NumSignatures: 1
Signature 1
Signature Verified
Number of Reference Digests = 2
Reference 1 digest is valid.
Reference 2 digest is valid.
```
However, despite the fact that the signature is already valid, the DIAN Colombia service still replies that it is incorrect.
(Regla: ZE02, Rechazo: Valor de la firma inválido)


File sent: 
[nie08920994992100000001_signed.txt](https://github.com/luisgoncalves/xades4j/files/7746851/nie08920994992100000001_signed.txt)

Response DIAN: 
[response_DIAN_.txt](https://github.com/luisgoncalves/xades4j/files/7746853/response_DIAN_.txt)

**Comment by luisgoncalves** [comment]
I still don't have strong reason to believe there's an issue in xades4j. Have you tried my suggestion above? I.e. write code to validate the signature using xades4j as well?

**Comment by YordyHz** [comment]
After some time investigating the problem it was due to an error in the header and the encoding which should be UTF-8.
The tag xmlns="dian:gov:co:facturaelectronica:NominaIndividual" was not being saved in the header.
Finally, it should be like this:

`<?xml version="1.0" encoding="UTF-8" standalone="no"?><NominaIndividual xmlns="dian:gov:co:facturaelectronica:NominaIndividual" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2" xmlns:xades="http://uri.etsi.org/01903/v1.3.2#" xmlns:xades141="http://uri.etsi.org/01903/v1.4.1#" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" SchemaLocation="" xsi:schemaLocation="dian:gov:co:facturaelectronica:NominaIndividual NominaIndividualElectronicaXSD.xsd">`

Problem solved, I stay tuned if anyone has similar problems.
