### ISSUE TITLE
Problems with signature validation

### ISSUE THREAD

**Issue by erotundo** [luisgoncalves/xades4j#251]
Hi!

I don't know if the project it's active and the example process it's not too explicit but i trying to use the library and validate the signature and not works. Maybe i'm doing something bad but the execution runs without problem and when i go to validate the signature throws exception in the certification store.

I'm running this project in windows so i don't know if i need a special configuration for the certification store

Thanks

**Comment by luisgoncalves** [comment]
Hi @erotundo ,

Your description is not very helpful... What's the exception that you're getting? Can you show a bit of your code, namely the configuration of the keying data provider (on production) and the certificate validation provider (on verification)?

The wiki contains limited exemples, but the tests have many more examples. Check the tests source code for reference.

**Comment by luisgoncalves** [comment]
Any updates?
