### ISSUE TITLE
Problem validating sign in https://ec.europa.eu/cefdigital/DSS/webapp-demo/validation

### ISSUE THREAD

**Issue by rubenpfer** [luisgoncalves/xades4j#254]
I'm generating xml signed with XadesEpesSigningProfile but when validating in https://ec.europa.eu/cefdigital/DSS/webapp-demo/validation I always get the error: The reference data object is not intact!. This is mi code:

  public void signXades(InputSource is, Writer writer) throws Exception {
	Document document = xmlUtil.parseDocument(is); 
	
	// Signature Policy
	SignaturePolicyInfoProvider policyInfoProvider = new SignaturePolicyInfoProvider() {
        public SignaturePolicyBase getSignaturePolicy() {
        	InputStream is = null;
        	try {
			  is = signaturePolicyFile.getInputStream();
			} catch (IOException e) {}
            return new SignaturePolicyIdentifierProperty(
                    new ObjectIdentifier(signaturePolicyUrl, 
                    	IdentifierType.URI, ""), is)
                      .withLocationUrl(signaturePolicyUrl);
        }
    };
    
	// Define the signing key/certificate
	KeyingDataProvider kp = new FileSystemKeyStoreKeyingDataProvider(keyStoreType, keyStoreFile.getInputStream(), 
			new FirstCertificateSelector(),
			new DirectPasswordProvider(keyStorePassword), new 
			DirectPasswordProvider(keyStorePassword), false);
	
	// Define the signed object
	DataObjectDesc obj = new DataObjectReference("")
			.withType("http://www.w3.org/2000/09/xmldsig#Object")
			.withTransform(new CanonicalXMLWithoutComments())
	        .withTransform(new EnvelopedSignatureTransform())
	        .withTransform(new XPathTransform("not(ancestor-or-self::ds:Signature)").withNamespace("ds", XMLNS))
	        .withDataObjectFormat(new DataObjectFormatProperty(MIME_TYPE, null).withIdentifier(new ObjectIdentifier(dataObjectFormatIdentifier, IdentifierType.OIDAsURN, "")));
	
	// Create the signature
	BasicSignatureOptions signatureOptions = new BasicSignatureOptions();
	signatureOptions.signKeyInfo(true);	
	signatureOptions.includePublicKey(true);
	XadesSigner signer = new XadesEpesSigningProfile(kp, policyInfoProvider).withBasicSignatureOptions(signatureOptions).newSigner();
	signer.sign(new SignedDataObjects(obj), document.getDocumentElement());	
	
    xmlUtil.writeDocument(document, writer, null);
    	
  }
[ejemplo.zip](https://github.com/luisgoncalves/xades4j/files/8060248/ejemplo.zip)

Attached file with xml before and after signing. Please, Can you help me to understand where is the problem?

**Comment by rubenpfer** [comment]
[util.zip](https://github.com/luisgoncalves/xades4j/files/8060495/util.zip)
Attached java source code

**Comment by rubenpfer** [comment]
I've also tested my signed xml in http://tools.chilkat.io/xmlDsigVerify.cshtml#generatedCode an the response is:

Signature is Invalid
Number of Reference Digests = 3
Reference 1 digest is invalid because the computed digest differs from the digest in the XML.
Reference 2 digest is invalid because the computed digest differs from the digest in the XML.
Reference 3 digest is invalid because the computed digest differs from the digest in the XML.

How digest is calculated? Is there missed some configuration in my code? Sorry if it's no problem with the library but I don't know where the problem is. Thanks in advance

**Comment by luisgoncalves** [comment]
At first glance your code looks ok.

- Why adding the "enveloped signature" transform and also the XPath transform? They seem redundant.
- Why adding the "object" type? The referenced nodeset is not a `ds:Object`

The digest of the references are calculated automatically by Apache XML Security (used by xades4j under the hood). There is one `Reference` for the `DataObjectReference` that you added, plus one for the signed properties, plus another to sign `KeyInfo`.

I suggest that you try with a simpler signature (e.g. a XAdES-BES) and take it from there.

**Comment by rubenpfer** [comment]
With XadesBesSigningProfile, and deleting the two points you advised to me, I've got the same problem. I don't understand because I have no control in digest. But the message is always the same: "digest is invalid because the computed digest differs from the digest in the XML". Any other suggestion?

**Comment by rubenpfer** [comment]
The problem was here:

.withTransform(new CanonicalXMLWithoutComments())

After commenting this line everything works. Thks for your help.
