### ISSUE TITLE
NoClassDefFoundError with XadesSigningProfile

### ISSUE THREAD

**Issue by LeonardoReino** [luisgoncalves/xades4j#257]
Good days
 I was having this problem to the moment to implement this library to my project, especific when I use KeyingDataProvider object and trying consume this with XadesBesSigningProfile for create a new signer. 

Windows 10 
Eclipse IDE/ Netbeans 12.6
Java 1.7
Xades4j 1.3.1
Electronic sign pfx active, that was probed in another programs from electronic signature

I used a lot of examples and versions from this library and changing Java version (Java 11 with Xades4j  v2 ) but exception is the same type. I was probe line by line the code and I noted that the problem is in  XadesBesSigningProfile

public class propia {

	

    public static void main(String[] args) throws Exception {
 
    	
    	
        class DirectPasswordProvider implements KeyStoreKeyingDataProvider.KeyStorePasswordProvider,
        KeyStoreKeyingDataProvider.KeyEntryPasswordProvider
        {
		    private char[] password;
		
		    public DirectPasswordProvider(String password)
		    {
		        this.password = password.toCharArray();
		    }
		
		    @Override
		    public char[] getPassword()
		    {
		        return password;
		    }
		
		    @Override
		    public char[] getPassword(String entryAlias, X509Certificate entryCert)
		    {
		        return password;
		    }
        }
           

        KeyingDataProvider keyingProvider = new FileSystemKeyStoreKeyingDataProvider(
                "pkcs12",
                "C:/Cert/mycert.pfx",
                new SigningCertSelector() {

                    @Override
                    public X509Certificate selectCertificate(List<X509Certificate> list) {
                        return list.get(0);
                    }
                },
                new DirectPasswordProvider("Pass"),
                new DirectPasswordProvider("Pass"),
                true);
    	
  
            XadesSigningProfile p = new XadesBesSigningProfile(keyingProvider); ////line of problem 
      
    }
	
	
	
}

The exception is the next 

Exception in thread "main" java.lang.NoClassDefFoundError: com/google/inject/Module
	at xades4j.production.XadesSigningProfile.<clinit>(XadesSigningProfile.java:91)
	at pruebac.propia.main(propia.java:102)
Caused by: java.lang.ClassNotFoundException: com.google.inject.Module
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 2 more

I hope can you helpme with that, like a said, when i migrated my code to Xades4j version 2 with Java 11 the response was the same
I read that this error could be due Java cant read POM from the library, but I dont know how force POM reader.

Thank you 

Esteban

**Comment by luisgoncalves** [comment]
Have you installed xades4j's dependencies? The missing class is from Guice, a library used by xades4j. Is Guice available in the classpath of your application? The same applies to Apache XML Security and Bouncy Castle.

https://github.com/luisgoncalves/xades4j/blob/master/pom.xml#L54
