### ISSUE TITLE
Key store has more than one private key entry

### ISSUE THREAD

**Issue by jonathan38m** [luisgoncalves/xades4j#260]
![image](https://user-images.githubusercontent.com/5795499/174506128-31783be7-798f-4040-98ee-e3a620cb5da9.png)

When I try to sign a file xml with my certification .p12 extension file. Appears this message.

I tried to find the error but only if I add this lines in the KeyStoreKeyingDataProvider.java in the getSigningCertificateChain() method  in the  245 line is fixed but I don't know if that is correct.

![image](https://user-images.githubusercontent.com/5795499/174506277-8179c3a8-a1f7-41f8-a444-7b9664963544.png)

My certification has two cert.

**Comment by luisgoncalves** [comment]
Right, the error means that the .p12 keystore has 2 private key entries, as you also mentioned.

From the stack trace, it seems that you're using `single()` as a certificate selector when creating the `FileSystemKeyStoreKeyingDataProvider`. As documented, that throws if there's more than one private key entry (signing certificate) in the key store.

In your case you need to provide a different implementation of `SigningCertificateSelector` that returns one of the available certificates based on some criteria (e.g. the entry alias or the certificate's DN).

```
FileSystemKeyStoreKeyingDataProvider
    .builder("pkcs12", "file.p12", new MyCertificateSelector())
    ....
```

http://luisgoncalves.github.io/xades4j/javadocs/2.0.0/reference/xades4j/providers/impl/KeyStoreKeyingDataProvider.SigningCertificateSelector.html
