### ISSUE TITLE
Invalid hash when signing

### ISSUE THREAD

**Issue by leanmaster** [luisgoncalves/xades4j#268]
Hi, I'm merging 4 XML into 1 and  signing a part of  XML file, but when I sign the file, it don't pass by https://verificador.iti.gov.br/verifier-2.10/ and presents a hash signature error, but if I separate only this part and submit to the verifier, the sign is ok. What is my fail? The part signed is the content of doc2 xml.

``
            Document doc = DocumentBuilderFactory
                    .newInstance()
                    .newDocumentBuilder()
                    .parse(f);
            Document doc2 = DocumentBuilderFactory
                    .newInstance()
                    .newDocumentBuilder()
                    .parse(dd);
            Document doc3 = DocumentBuilderFactory
                    .newInstance()
                    .newDocumentBuilder()
                    .parse(tdpd);
            Document doc4 = DocumentBuilderFactory
                    .newInstance()
                    .newDocumentBuilder()
                    .parse(tre);
            Document doc5 = DocumentBuilderFactory
                    .newInstance()
                    .newDocumentBuilder()
                    .parse(tdc);

            Element elem = doc.getDocumentElement();
            Node nodeList;
            Node first1DocImportedNode = doc.importNode(doc2.getFirstChild(), true);
            elem.appendChild(first1DocImportedNode);

            Node secondDoc = doc.importNode(doc3.getFirstChild(), true);
            elem.appendChild(secondDoc);
            Node firstDocImportedNode = doc.importNode(doc4.getFirstChild(), true);
            elem.appendChild(firstDocImportedNode);
            firstDocImportedNode = doc.importNode(doc5.getFirstChild(), true);
            elem.appendChild(firstDocImportedNode);
            nodeList = doc.getElementsByTagName("DadosDiploma").item(0);

            Element headerElement = null;
            Element dados = doc2.getDocumentElement();
            Element dadostdpd = doc3.getDocumentElement();
            Element dadostre = doc4.getDocumentElement();
            Element dadostdc = doc5.getDocumentElement();

            if (first1DocImportedNode instanceof Element) {
                headerElement = (Element) first1DocImportedNode;
                DOMHelper.useIdAsXmlId(headerElement);
                headerElement.setIdAttribute("id", true);
            }

            KeyingDataProvider kdp = FileSystemKeyStoreKeyingDataProvider
                    .builder("PKCS12", CERT_FOLDER + CERT, KeyStoreKeyingDataProvider.SigningCertificateSelector.single())
                    .storePassword(new DirectPasswordProvider(PASS))
                    .entryPassword(new DirectPasswordProvider(PASS))
                    .fullChain(true)
                    .build();
            KeyingDataProvider kdp2 = FileSystemKeyStoreKeyingDataProvider
                    .builder("PKCS12", CERT_FOLDER + CERT2, KeyStoreKeyingDataProvider.SigningCertificateSelector.single())
                    .storePassword(new DirectPasswordProvider(PASS2))
                    .entryPassword(new DirectPasswordProvider(PASS2))
                    .fullChain(true)
                    .build();

            DOMHelper.useIdAsXmlId(headerElement);

            DataObjectDesc obj = new DataObjectReference("#" + dados.getAttribute("id"))
                    .withTransform(new EnvelopedSignatureTransform())
                    .withTransform(new XPathTransform("not(ancestor-or-self::ds:Signature)"))
                    .withTransform(new GenericAlgorithm("http://www.w3.org/2001/10/xml-exc-c14n#"))
                    .withDataObjectFormat(new DataObjectFormatProperty("text/xml"));

            SignatureAlgorithms algorithms = new SignatureAlgorithms();//.withCanonicalizationAlgorithmForSignature(new ExclusiveCanonicalXMLWithoutComments());
            algorithms.withCanonicalizationAlgorithmForSignature(new ExclusiveCanonicalXMLWithoutComments());

            SignedDataObjects dataObjs = new SignedDataObjects().withSignedDataObject(obj);

            XadesSigner signer = new XadesBesSigningProfile(kdp).newSigner();
            XadesSigner signer2 = new XadesBesSigningProfile(kdp2).newSigner();
            XadesSigner.SignatureAppendingStrategy sas = SignatureAppendingStrategies.AsLastChild;

            signer.sign(dataObjs, first1DocImportedNode, sas);
            signer2.sign(dataObjs, first1DocImportedNode, sas);

            TransformerFactory tFactory = TransformerFactory.newInstance();
            Transformer transformer = tFactory.newTransformer();
            transformer.setOutputProperty(OutputKeys.INDENT, "no");
            transformer.setOutputProperty(OutputKeys.OMIT_XML_DECLARATION, "yes");

            DOMSource source = new DOMSource(doc);
            DOMSource source2 = new DOMSource(doc2);

            String newName = f.getAbsolutePath().replaceFirst(".xml$", "_assinado.xml");
            File novoArquivo = new File(newName);
            StreamResult result = new StreamResult(novoArquivo); 
            StringWriter writer = new StringWriter();
            transformer.transform(source, result);

**Comment by leanmaster** [comment]
Agora q vi q vc é português... Estou juntando os 4 XML em um só e assinando só a parte do XML doc2, Quando passo pelo verificador o arquivo gerado com a assinatura ele dá erro do resumo criptográfico, mas se separo só a parte referente à parte assinada ele dá OK. Qual a bobagem que estou fazendo?

**Comment by luisgoncalves** [comment]
Olá. Sim sou, mas sugiro manter a conversa em inglês porque pode ser útil para outras pessoas.

Do you mean that if you use the output of `source2` the validation passes but with the output of `source` it doesn't? I don't know what `importNode` does exactly, but perhaps it has some caveats. Have you tried setting the different `DocumentBuilderFactory` instances to be namespace aware (`setNamespaceAware(true)`?

Also, to rule out other issues, perhaps try merging the docs, the outputting to an intermediate file, then parsing that to apply the signature.

**Comment by leanmaster** [comment]
thank you, you did what I asked, but I found out that I need to sign the part separately and then attach it, but following a specific policy (http://politicas.icpbrasil.gov.br/PA_AD_RB_v2_4.xml). Do I need to open a new issue? This policy includes a reference to the document itself (from what I understand a hash or something similar of the document itself)

**Comment by luisgoncalves** [comment]
I guess you need a XAdES-EPES signature.

- http://luisgoncalves.github.io/xades4j/javadocs/2.0.0/reference/xades4j/production/XadesEpesSigningProfile.html
- http://luisgoncalves.github.io/xades4j/javadocs/2.0.0/reference/xades4j/properties/SignaturePolicyIdentifierProperty.html

Using the above types ensures that the signature contains the needed `SignaturePolicyIdentifier` qualifying property. The `SignaturePolicyIdentifierProperty` should be created by passing the contents of the policy document. xades4j handles the hashing et al.

**Comment by leanmaster** [comment]
This?

            SignaturePolicyInfoProvider policyInfoProvider = new SignaturePolicyInfoProvider() {
                @Override
                public SignaturePolicyBase getSignaturePolicy() {
                    return new SignaturePolicyIdentifierProperty(
                            new ObjectIdentifier("urn:oid:2.16.76.1.7.1.6.2.4",
                                    IdentifierType.OIDAsURN,
                                    ""),
                            this.getClass().getResourceAsStream("/PA_AD_RB_v2_4.xml")
                    );
                }
            };
            XadesSigner signer1 = new XadesEpesSigningProfile(kdp, policyInfoProvider)
                    .newSigner();

**Comment by luisgoncalves** [comment]
Yes, that should do it as far as indicating the policy goes. Note that xades4j won't do anything else with the policy document - i.e. the policy rules are not processed/enforced in any way.

You need to configure xades4j to produce signatures that comply to the policy. I'm not very familiar with the policy XML format, but that policy seems to require the `SigningCertificate` and `SignaturePolicyIdentifier` properties, which the code on the previous comment achieves.

I also see some references to specific algorithms, but I think the default xades4j settings match those requirements.

**Comment by leanmaster** [comment]
Almost ok, The two mandatory attributes are missing: SigningCertificate and SignaturePolicyIdentifier. Are they into policy properties?

**Comment by luisgoncalves** [comment]
What do you mean? xades4j should add those two qualifying properties. Doesn't the output XML contain them?

**Comment by leanmaster** [comment]
Correcting Me... The verifier is saying: Disapproved. No certificate in signing matches SigningCertificate information... and... 
Disapproved. The cryptographic summary of the policy is incorrect (SignaturePolicyIdentifier)

**Comment by luisgoncalves** [comment]
> No certificate in signing matches SigningCertificate information

The policy seems to mandate some particular trust roots (CAs). Are you using a certificate/key that is issued by those CAs?

The policy also has `MandatedCertificateRef`/`MandatedCertificateInfo`, but xades4j includes the signing certificate by default, so those rules should be matched...

> The cryptographic summary of the policy is incorrect 

Your code seems correct. It's possible that xades4j has a bug around the generation of the `SignaturePolicyIdentifier` property..

**Comment by leanmaster** [comment]
The certificate is issued by requested CA...

**Comment by luisgoncalves** [comment]
I don't think I can help much more with the SigningCertificate issue. Perhaps you could try to get more information about the policy requirements and/or the verification failures from the verifier. 

Regarding `SignaturePolicyIdentifier`, the XAdES spec says that the policy document should be processed according to XML-DSIG reference/transform processing rules. xades4j doesn't add any transforms, and it just hashes the policy document. I guess that to match XML-DSIG processing, it may need to to canonicalization. I'll try to investigate more when I have some time, but you can also try to do so. Do you have access to a signature that is accepted by that verifying system? Even if it is only the `SignaturePolicyIdentifier` element. It would be great to use it for testing.

**Comment by leanmaster** [comment]
Yes, I have. This is a valid:
<xades:SignaturePolicyIdentifier>
<xades:SignaturePolicyId>
<xades:SigPolicyId>
<xades:Identifier Qualifier="OIDAsURN">urn:oid:2.16.76.1.7.1.6.2.4</xades:Identifier>
</xades:SigPolicyId>
<xades:SigPolicyHash>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>V1oxev3+Z5tia7oVifHtePiXskTb6LP9K1QE2u1zoV4=</ds:DigestValue>
</xades:SigPolicyHash>
<xades:SigPolicyQualifiers>
<xades:SigPolicyQualifier>
<xades:SPURI>http://politicas.icpbrasil.gov.br/PA_AD_RB_v2_4.xml</xades:SPURI>
</xades:SigPolicyQualifier>
</xades:SigPolicyQualifiers>
</xades:SignaturePolicyId>
</xades:SignaturePolicyIdentifier>
And it was generated by my code
<xades:SignaturePolicyIdentifier>
<xades:SignaturePolicyId>
<xades:SigPolicyId>
<xades:Identifier Qualifier="OIDAsURN">urn:oid:2.16.76.1.7.1.6.2.4</xades:Identifier>
<xades:Description/>
</xades:SigPolicyId>
<xades:SigPolicyHash>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>UCXZi0JhM3ioo0h9qX00IKJz4WSaAVUM/P83tg2c0vk=</ds:DigestValue>
</xades:SigPolicyHash>
<xades:SigPolicyQualifiers>
<xades:SigPolicyQualifier>
<xades:SPURI>http://politicas.icpbrasil.gov.br/PA_AD_RB_v2_4.xml</xades:SPURI>
</xades:SigPolicyQualifier>
</xades:SigPolicyQualifiers>
</xades:SignaturePolicyId>
</xades:SignaturePolicyIdentifier>

**Comment by leanmaster** [comment]
Maybe <code><xades:Description/><code>? The hash modify with this information. How to ommit this?

**Comment by luisgoncalves** [comment]
> Maybe `xades:Description/`? The hash modify with this information. How to ommit this?

I don't think so, because the digest is of the policy document itself, and `xades:Description` is not part of that document.

**Comment by leanmaster** [comment]
Hi, I found a difference in SignedInfo, maybe some transform needed. This is a valid:
<code><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/><ds:Reference Id="RefSignProp-1656794625548" Type="http://uri.etsi.org/01903#SignedProperties" URI="#SigProperties-1656794625548"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ds:DigestValue>yl8Fok+75l374LcfSxNYHjvNXO95rVBXYp0TyEIeC2E=</ds:DigestValue></ds:Reference><ds:Reference Id="RefElement-1656794625548" URI="#Dip82231126984196635000867574347880902547205583"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ds:Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116"><ds:XPath>not(ancestor-or-self::ds:Signature)</ds:XPath></ds:Transform><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ds:DigestValue>Wy8P17CrTgHNaoQ47P+3sXW70sOt5eSz9E9jCcSwHRM=</ds:DigestValue></ds:Reference></ds:SignedInfo></code>
 
and this is the SignedInfo generated by my code:

<code><ds:SignedInfo>
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
<ds:Reference Id="xmldsig-52ea6f5e-6e95-48ed-a3ef-6701dc6740f8-ref0" URI="#Dip00216010059420220000002797691410042015000001">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
<ds:Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116"><ds:XPath>not(ancestor-or-self::ds:Signature)</ds:XPath></ds:Transform>
<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>zMRW42VZTd7iGvV1u+WS/gXp6IPvUO5h78rfpucf0T8=</ds:DigestValue>
</ds:Reference>
<ds:Reference Type="http://uri.etsi.org/01903#SignedProperties" URI="#xmldsig-52ea6f5e-6e95-48ed-a3ef-6701dc6740f8-signedprops">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>FKFCAIZBl0o2m0wiTW2jhofBTSq9LfRR9v5yI1gMpxo=</ds:DigestValue>
</ds:Reference>
</ds:SignedInfo></code>

**Comment by luisgoncalves** [comment]
xades4j also adds the reference to signed properties; it's there on your XML (`URI="#xmldsig-f2543b0d-8632-4e19-840f-ff93b63efe4a-signedprops"`).

The supposedly correct `SignaturePolicyIdentifier` that you provided has a digest of `V1oxev3+Z5tia7oVifHtePiXskTb6LP9K1QE2u1zoV4=`, which is the same as contained in the `SignPolicyDigest` element of the policy document. I don't think this is correct. The XAdES rules for `SignaturePolicyIdentifier` (section G.2.2.6 of https://uri.etsi.org/01903/v1.3.2/ts_101903v010302p.pdf) say:

> Retrieve the electronic document containing the details of the policy, and identified by the contents of
SigPolicyId element. Apply the transformations indicated in the ds:Transforms element of
SignaturePolicyId, compute the digest of the resulting document using the algorithm indicated in
ds:DigestMethod and check its value with the digest value present in ds:DigestMethod

Since there aren't any transforms defined in `SignaturePolicyIdentifier`, my understanding is that the whole policy document (binary) should be digested, which is what xades4j does.

It seems that the verifying system is using a different criteria.

**Comment by leanmaster** [comment]
I've been analyzing several valid signatures and you are right, the policy uses the SignPolicyDigest as Digest. I will need to override the method that xades4j uses for my signature to be considered valid. What method do I need to override to meet this need, which, although it is wrong, I need to follow?

**Comment by luisgoncalves** [comment]
There's no configuration option or similar that would allow you to change this, because the behavior is hard-coded in xades4j.

This would require changes in the library, probably:
- [DataGenSigPolicy](https://github.com/luisgoncalves/xades4j/blob/master/src/main/java/xades4j/production/DataGenSigPolicy.java)
- [SignaturePolicyIdentifierProperty](https://github.com/luisgoncalves/xades4j/blob/master/src/main/java/xades4j/properties/SignaturePolicyIdentifierProperty.java)

I'm not sure about supporting this in the library, as it's not standard behavior. I guess you can do the changes for yourself. A possible approach would be to have something like a "digest override" in `SignaturePolicyIdentifierProperty`, and then use that in `DataGenSigPolicy` instead of calculating the digest of the policy document. Doesn't seem like a clean fit.

**Comment by leanmaster** [comment]
I change DataGenSigPolicy and SignaturePolicyIdentifier is ok, but it has problem in SigningCertificate. My certificate complies with the policy. Where is added &#13; in digest values? Can be this?

**Comment by luisgoncalves** [comment]
I don't know. Do you have details of the error? Is it still `No certificate in signing matches SigningCertificate information`?

Did you change the default `BasicSignatureOptions`, namely `includeSigningCertificate()`? As I mentioned before, by default xades4j includes the signing certificate in `KeyInfo` and hashes of all the certificates returned by the `KeyingDataProvider` in the `SigningCertificate` qualifying property. This seems to match what the policy requires.. You probably should ask the verifier for more details or documentation.

In any case, the `SigningCertificate` property is created by the `DataGenSigningCertificate` class.

**Comment by leanmaster** [comment]
I noticed that other valid signatures always have <code>DigestValue</code> in the <code>CertDigest</code> different from the one generated by my code (and they are always the same) using the same certificate. Maybe the brazilian policy uses another way to generate as the <code>SignaturePolicyIdentifier</code>. I'm already annoyed by this and understand that it's not the framework's fault

**Comment by leanmaster** [comment]
And this is only the first problem that I have... I need to make a XML like this image:
![padrao](https://user-images.githubusercontent.com/83795066/210467526-b4a2c5a8-debb-45fd-b321-849b73cb1ea9.png)

**Comment by leanmaster** [comment]
I'm in the AD-RB yet, but to the timestamp I have a signer that does the job...

**Comment by luisgoncalves** [comment]
> I noticed that other valid signatures always have DigestValue in the CertDigest different from the one generated by my code 

I guess each signature is produced by a different key pair (e.g. your personal key or your company's key), so digests from other signatures should be different.

> I'm in the AD-RB yet, but to the timestamp I have a signer that does the job...

It's really hard for me to provide guidance on how to configure xades4j based on these loose requirements. If I see references to "timestamps", I assume you'd need a XAdES-T signature. xades4j can also produce those, using [`XadesTSigningProfile`](http://luisgoncalves.github.io/xades4j/javadocs/2.0.0/reference/xades4j/production/XadesTSigningProfile.html). More info: https://github.com/luisgoncalves/xades4j/wiki/Timestamping. It's not clear if this is the requirement, though.

**Comment by luisgoncalves** [comment]
Glad that you managed to get it to work. You're welcome.
