### ISSUE TITLE
Migrating from Xades4j 1.7.0 to Xades4j 2.2.0

### ISSUE THREAD

**Issue by ricposace** [luisgoncalves/xades4j#270]
Hello Luis

I've been using Xades4j 1.7.0 for few year now,

I want to migrate to Xades4j 2.2.0

My working code:

XadesSigner signer1 = new XadesEpesSigningProfile(kdp, policyInfoProvider)
                    .withBasicSignatureOptions(bso)
                    .withSignaturePropertiesProvider(new SignaturePropertiesProvider() {
                        @Override
                        public void provideProperties(SignaturePropertiesCollector arg0) {
                            SigningTimeProperty sigTime = new SigningTimeProperty();
                            arg0.setSignerRole(new SignerRoleProperty().withClaimedRole("supplier"));
                            arg0.setSigningTime(sigTime );
                        }
                    })
                    .withAlgorithmsProviderEx(new AlgorithmsProviderEx() {
                        @Override
                        public Algorithm getSignatureAlgorithm(String string) throws UnsupportedAlgorithmException {
                            return new GenericAlgorithm("http://www.w3.org/2001/04/xmldsig-more#rsa-sha256");

                        }
                        @Override
                        public Algorithm getCanonicalizationAlgorithmForSignature() {
                                //segun la DIAN debe ser Canonical XML (omits comments) que debe generar ï¿½http://www.w3.org/TR/2001/REC-xml-c14n-20010315ï¿½ dentro del elemento <CanonicalizationMethod>
                                //return new GenericAlgorithm(Canonicalizer.ALGO_ID_C14N_EXCL_OMIT_COMMENTS);
                                return new GenericAlgorithm(Canonicalizer.ALGO_ID_C14N_OMIT_COMMENTS);
                        }
                        @Override
                        public Algorithm getCanonicalizationAlgorithmForTimeStampProperties() {
                                //return new GenericAlgorithm(Canonicalizer.ALGO_ID_C14N_EXCL_OMIT_COMMENTS);
                                return new GenericAlgorithm(Canonicalizer.ALGO_ID_C14N_OMIT_COMMENTS);
                        }
                        @Override
                        public String getDigestAlgorithmForDataObjsReferences() {
                                // TODO Auto-generated method stub
                                //return ;
                                return "http://www.w3.org/2001/04/xmlenc#sha256";
                        }
                        @Override
                        public String getDigestAlgorithmForReferenceProperties() {
                                // TODO Auto-generated method stub
                                return "http://www.w3.org/2001/04/xmlenc#sha256";
                        }
                        @Override
                        public String getDigestAlgorithmForTimeStampProperties() {
                                // TODO Auto-generated method stub
                                return "http://www.w3.org/2001/04/xmlenc#sha256";
                        }
                })
               .newSigner();

But when I include new dependency fails with compiling error in this part 

.withAlgorithmsProviderEx(new AlgorithmsProviderEx() { ....

It seems .withAlgorithmsProviderEx has been removed.

How can I modify my code in order to compile with new version?

**Comment by luisgoncalves** [comment]
Hi.

Please go through the docs and release notes when upgrading, namely to a new major version. There's an upgrade guide that should cover all the breaking changes.

- https://github.com/luisgoncalves/xades4j/wiki/Migrating#migration-guide
- https://github.com/luisgoncalves/xades4j/releases
