### ISSUE TITLE
Upgrade Apache Santuario to version 4.X.X

### ISSUE THREAD

**Issue by luisgoncalves** [luisgoncalves/xades4j#277]
There are some changes to `XmlSignatureInput` types which need to be checked carefully.

**Comment by mjechow** [comment]
I started a branch for this issue: https://github.com/mjechow/xades4j/tree/mje/xmlsec

**Comment by luisgoncalves** [comment]
In `TimeStampDigestInputImpl`, I see you wrote:

```
digestInput.write(refData.getBytes());
```

I've checked `XMLSignatureInput`'s `getBytes` and `write` methods, and I think we could use:

```
refData.write(digestInput);
```

It's slightly better if the `XMLSignatureInput` represents a Stream, as it avoids reading it into byte[]. WDYT? Can you put that up as a PR?

----

I'm now seeing that `XMLSignatureInput` actually handles canonicalization, so the code in `TimeStampDigestInputImpl` is a bit redundant. Anyway, since it is there, we know that in the end `refData` always contains bytes or a stream, so it won't canonicalize again. That code can later get a clean up, as it requires limiting a bit what C14N algorithms can be configured in xades4j via `SignatureAlgorithms`, which would be a breaking change.

**Comment by mjechow** [comment]
yes, of course. I forgot that change.
