### ISSUE TITLE
Question: How to Sign with Three References

### ISSUE THREAD

**Issue by hanadderia** [luisgoncalves/xades4j#288]
I'm unsure if requesting assistance here is permitted, but I'm currently facing challenges with the library. As someone new to Java, I'm having difficulties. I will provide both the original XML and the signed XML for reference. Perhaps there's an example of my requirement that I may have overlooked.

Original Message:

```xml
<FPEnvelope xmlns="urn:iso:std:iso:20022:tech:xsd:verification_request"
    xmlns:document="urn:iso:std:iso:20022:tech:xsd:acmt.023.001.03"
    xmlns:header="urn:iso:std:iso:20022:tech:xsd:head.001.001.03">
    <header:AppHdr>
        <header:BizMsgIdr>DAHISOS0419811268246516890240</header:BizMsgIdr>
        <header:MsgDefIdr>acmt.023.001.03</header:MsgDefIdr>
        <header:CreDt>2024-07-16T11:00:45.045Z</header:CreDt>
    </header:AppHdr>
    <document:Document>
        <!-- Ommited -->
    </document:Document>
</FPEnvelope>
```

The signature must be included within the header:AppHdr tag, positioned as the final child element. The KeyInfo element should exclusively contain the certificate serial number and issuer name. The signing properties should solely include the signing time. The signature should contain three references: the first pointing to the KeyInfo, the second to the signing properties, and the third to the document:Document node of the original XML and should be URI-less.

Signed XML 

```xml
<FPEnvelope xmlns="urn:iso:std:iso:20022:tech:xsd:verification_request"
    xmlns:document="urn:iso:std:iso:20022:tech:xsd:acmt.023.001.03"
    xmlns:header="urn:iso:std:iso:20022:tech:xsd:head.001.001.03">
    <header:AppHdr>
        <header:BizMsgIdr>DAHISOS0419811268246516890240</header:BizMsgIdr>
        <header:MsgDefIdr>acmt.023.001.03</header:MsgDefIdr>
        <header:CreDt>2024-07-16T11:00:45.045Z</header:CreDt>
        <document:Sgntr xmlns:document="urn:iso:std:iso:20022:tech:xsd:head.001.001.03">
            <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                <ds:SignedInfo>
                    <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                    <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
                    <ds:Reference URI="#_381418ca-29c0-4647-8dc0-5b0e7be657d3">
                        <ds:Transforms>
                            <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                        </ds:Transforms>
                        <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                        <ds:DigestValue>BpPlPn/C7TSyWekuigdtoSLElv+Jw2kG3n5bp5NXcVs=</ds:DigestValue>
                    </ds:Reference>
                    <ds:Reference Type="http://uri.etsi.org/01903/v1.3.2#SignedProperties" URI="#_89cd7f07-c1cb-4a4a-a56b-0ccf235d730d-signedprops">
                        <ds:Transforms>
                            <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                        </ds:Transforms>
                        <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                        <ds:DigestValue>AmPgfzZcy8Fx2v33uFNcV8RJ9bYwTpxOT/6fT2wGCcc=</ds:DigestValue>
                    </ds:Reference>
                    <ds:Reference>
                        <ds:Transforms>
                            <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                        </ds:Transforms>
                        <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                        <ds:DigestValue>5D5OBwoWiY2242f+9hLTNxfCPViZmSty2bxA1pFj28g=</ds:DigestValue>
                    </ds:Reference>
                </ds:SignedInfo>
                <ds:SignatureValue>11bUMoP/Nv48X0bu3xfRFbL+zLpYtToQ4YBP2qu8NVAlLNGtf/Y7zWUKa9cv3W9lQ8c3/upABLbeO1wunauckyDTXaZZvyihQ4KDrSVgY5U87M5ITreNYlOPFOGbzCXCKvjsVUuwdVQduHo2Nnu/lmW0b08edskdjJAchWvv4uqJ0/YUoW3sPemMnHQfIq/6vyhBkJT1p+JGgMuSqkuDmD8qomBq7Nicmu1D98H1tli19r8TlFuXb+AByeDT+GviVe2lo8OJKjAKtuSRMHtj4cD+nbQzdrnsJ4/HaL2v3s+Lyq+bfE2f5rFwmVbobZdo2daN2cQl133+2mmHSlVQSw==</ds:SignatureValue>
                <ds:KeyInfo Id="_381418ca-29c0-4647-8dc0-5b0e7be657d3">
                    <ds:X509Data>
                        <ds:X509IssuerSerial>
                            <ds:X509IssuerName>CN=sps issuing CA, DC=sps, DC=local</ds:X509IssuerName>
                            <ds:X509SerialNumber>2720690914248401994061170977080268875322359813</ds:X509SerialNumber>
                        </ds:X509IssuerSerial>
                    </ds:X509Data>
                </ds:KeyInfo>
                <ds:Object>
                    <xades:QualifyingProperties xmlns:xades="http://uri.etsi.org/01903/v1.3.2#">
                        <xades:SignedProperties Id="_89cd7f07-c1cb-4a4a-a56b-0ccf235d730d-signedprops">
                            <xades:SignedSignatureProperties>
                                <xades:SigningTime>2024-07-16T11:00:45Z</xades:SigningTime>
                            </xades:SignedSignatureProperties>
                        </xades:SignedProperties>
                    </xades:QualifyingProperties>
                </ds:Object>
            </ds:Signature>
        </document:Sgntr>
    </header:AppHdr>
    <document:Document>
      <!-- Ommited -->
    </document:Document>
</FPEnvelope>
```

**Comment by luisgoncalves** [comment]
This kind of question is better suited for SO, please do that next time.

I can't help you with learning Java, but did you check the Wiki and Javadocs at all? It should contain everything you need.
Anyway, I'll provide more pointers on how to configure xades4j to achieve a signature like the one in your example.

Start by checking the [overview](https://github.com/luisgoncalves/xades4j/wiki/SignatureProduction). Looks like you want a XAdES-BES signature, so use `XadesBesSigningProfile`.

> The KeyInfo element should exclusively contain the certificate serial number and issuer name.

This can be controlled using `BasicSignatureOptions`:
- https://github.com/luisgoncalves/xades4j/wiki/OtherSigningOptions#keyinfo-content
- http://luisgoncalves.github.io/xades4j/javadocs/2.2.0/reference/xades4j/production/BasicSignatureOptions.html
- An instance of this type is [configured in the signing profile](http://luisgoncalves.github.io/xades4j/javadocs/2.2.0/reference/xades4j/production/XadesSigningProfile.html#withBasicSignatureOptions(xades4j.production.BasicSignatureOptions)).

> The signing properties should solely include the signing time.

This is already the default behavior, but [can be overridden](https://github.com/luisgoncalves/xades4j/wiki/DefiningQualifyingProperties#optional-signature-properties).

> The signature should contain three references: the first pointing to the KeyInfo

Configure this via the ` signKeyInfo` method in `BasicSignatureOptions`. The library will include the reference automatically when set to true.

> The signature should contain three references: ... the second to the signing properties

This is always added automatically by the library.

> The signature should contain three references: ... the third to the document:Document node of the original XML and should be URI-less.

This is the actual "signed resource". It's a bit weird that it is a URI-less reference, but you can tell the library to sign such resource using `AnonymousDataObjectReference` (see https://github.com/luisgoncalves/xades4j/wiki/DefiningSignedResources).

That type of signed resource is usually meant for out-of-band binary data, so using it with a document node is not direct. You'll have to find a way to get a `Stream` from the `document:Document` element. A possible way is to transform the `Node` into a `ByteArrayOutputStream`. See [here](https://github.com/luisgoncalves/xades4j/blob/master/src/test/java/xades4j/utils/SignatureServicesTestBase.java#L118) for an example.

> The signature must be included within the header:AppHdr tag, positioned as the final child element.

xades4j only creates `ds:Signature`. You'll need to create the `document:Sgntr` element yourself and pass it as the parent node to [`XadesSigner#sign`](http://luisgoncalves.github.io/xades4j/javadocs/2.2.0/reference/xades4j/production/XadesSigner.html#sign(xades4j.production.SignedDataObjects,%20org.w3c.dom.Node)).

----

Hope this helps!

**Comment by hanadderia** [comment]
Hello @luisgoncalves Thank you very much, 

I couldn't succeed to remove this from SignedSignatureProperties in QualifyingProperties

```xml
<xades:SigningCertificate>
    <xades:Cert>
        <xades:CertDigest>
            <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
            <ds:DigestValue>****************=</ds:DigestValue>
        </xades:CertDigest>
        <xades:IssuerSerial>
            <ds:X509IssuerName>******************</ds:X509IssuerName>
            <ds:X509SerialNumber>****************</ds:X509SerialNumber>
        </xades:IssuerSerial>
    </xades:Cert>
</xades:SigningCertificate>
```
This is were I was trying to override the behavior:

```java
    private static BasicSignatureOptions getSignatureOptions() {
        BasicSignatureOptions signatureOptions = new BasicSignatureOptions();
        signatureOptions.signKeyInfo(true);
        signatureOptions.includeIssuerSerial(true);
        signatureOptions.includeSigningCertificate(SigningCertificateMode.NONE);
        signatureOptions.includePublicKey(false);
        signatureOptions.checkCertificateValidity(true);
        return signatureOptions;
    }

    private static XadesBesSigningProfile getSigningProfile(KeyingDataProvider kdp) {
        XadesBesSigningProfile profile = new XadesBesSigningProfile(kdp);
        profile.withBasicSignatureOptions(getSignatureOptions());
        profile.withSignaturePropertiesProvider(new SignaturePropertiesProvider() {
            @Override
            public void provideProperties(SignaturePropertiesCollector signedPropsCol) {
                Calendar c = Calendar.getInstance(TimeZone.getTimeZone("GMT"));
                c.clear();
                c.setTime(new Date());
                c.set(Calendar.HOUR_OF_DAY, 0);
                c.set(Calendar.MINUTE, 0);
                c.set(Calendar.SECOND, 0);
                c.set(Calendar.MILLISECOND, 0);
                signedPropsCol.setSigningTime(new SigningTimeProperty(c));
            }
        });

        profile.withSignatureAlgorithms(new SignatureAlgorithms()
                .withSignatureAlgorithm("RSA", XMLSignature.ALGO_ID_SIGNATURE_RSA_SHA1)
                .withCanonicalizationAlgorithmForSignature(new GenericAlgorithm(ALGO_ID_C14N_EXCL_OMIT_COMMENTS))
                // .withDigestAlgorithmForReferenceProperties(ALGO_ID_DIGEST_SHA1)
                .withDigestAlgorithmForDataObjectReferences(ALGO_ID_DIGEST_SHA256));

        return profile;
    }
```

**Comment by luisgoncalves** [comment]
For reference: the question about the SigningCertificate property is being discussed in SO: https://stackoverflow.com/questions/78803576/remove-signing-certificate-from-qualifying-properties-xades4j
