### ISSUE TITLE
Regla: ZE02, Rechazo: Valor de la firma inválido. Al Generar Factura Electronica para DIAN Colombia

### ISSUE THREAD

**Issue by smejia010** [luisgoncalves/xades4j#310]
He estado algunos días atascado en este error y no he podido encontrar la razón por la cual sucede. Lo estoy realizando en C#
Regla: ZE02, Rechazo: Valor de la firma inválido.
Adjuntaré el los archivos del codigo con el cual estoy generando e insertando la Firma y el XML que genera.

[FirmadorV2.zip](https://github.com/user-attachments/files/17272350/FirmadorV2.zip)

**Comment by luisgoncalves** [comment]
Hi

Please use English when creating tickets, as I'm not Spanish speaker.

It's not clear how your issue related to xades4j, since you're writing C# code, not using xades4j. Therefore, I'm closing this ticket. If you have an issue specific to xades4j, please add more details.
