### ISSUE TITLE
Difficulties to add tag SignaturePolicyIdentifier

### ISSUE THREAD

**Issue by GoogleCodeExporter** [luisgoncalves/xades4j#63]
```
Hi,

Firstly, all my best wishes to all of you :)

 I have difficulties to add this tags :
<xad:SignaturePolicyIdentifier>
    <xad:SignaturePolicyId>
        <xad:SigPolicyId><xad:Identifier>urn:oid:1.2.250.1.131.1.5.18.21.1.4</xad:Identifier>
<xad:Description>Politique de signature Helios de la DGFiP</xad:Description>
        </xad:SigPolicyId>
        <xad:SigPolicyHash>
            <xad:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
            <xad:DigestValue>Jkdb+aba0Hz6+ZPKmKNhPByzQ+Q=</xad:DigestValue>
        </xad:SigPolicyHash>
        <xad:SigPolicyQualifiers>
            <xad:SigPolicyQualifier>
                <xad:SPURI>https://portail.dgfip.finances.gouv.fr/documents/PS_Helios_DGFiP.pdf</xad:SPURI>
            </xad:SigPolicyQualifier>
        </xad:SigPolicyQualifiers>
    </xad:SignaturePolicyId>
</xad:SignaturePolicyIdentifier>

I can get this :
<xades:SignaturePolicyIdentifier>
    <xades:SignaturePolicyId>
        <xades:SigPolicyId>
            <xades:Identifier>urn:oid:1.2.563</xades:Identifier>
        </xades:SigPolicyId>
        <xades:SigPolicyHash>
            <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
            <ds:DigestValue>Jkdb+aba0Hz6+ZPKmKNhPByzQ+Q=</ds:DigestValue>
        </xades:SigPolicyHash>
    </xades:SignaturePolicyId>
</xades:SignaturePolicyIdentifier>

I'm using this code:
XadesSigningProfile p = new XadesTSigningProfile(kp)
                 .withPolicyProvider(new SignaturePolicyInfoProvider() {
                    @Override
                    public SignaturePolicyBase getSignaturePolicy() {
                         try {
                             return new SignaturePolicyIdentifierProperty(new ObjectIdentifier("urn:oid:1.2.563"),
                                     new URL("https://portail.dgfip.finances.gouv.fr/documents/PS_Helios_DGFiP.pdf").openStream());
                         } catch (MalformedURLException ex) {
                             Logger.getLogger(StelaSign.class.getName()).log(Level.SEVERE, null, ex);
                             return new SignaturePolicyImpliedProperty();
                         } catch (IOException ex) {
                             Logger.getLogger(StelaSign.class.getName()).log(Level.SEVERE, null, ex);
                             return new SignaturePolicyImpliedProperty();
                         }
                    }
                 })               
                  .withAlgorithmsProviderEx(new AlgorithmsProviderEx() {
                    @Override
                    public Algorithm getSignatureAlgorithm(String string) throws UnsupportedAlgorithmException {
                       return new GenericAlgorithm(XMLSignature.ALGO_ID_SIGNATURE_RSA_SHA1);
                    }
                    @Override
                    public Algorithm getCanonicalizationAlgorithmForSignature() {
                        //return new GenericAlgorithm(Canonicalizer.ALGO_ID_C14N_WITH_COMMENTS);
                        return new GenericAlgorithm(Canonicalizer.ALGO_ID_C14N_EXCL_OMIT_COMMENTS);
                    }
                    @Override
                    public Algorithm getCanonicalizationAlgorithmForTimeStampProperties() {
                        //return new GenericAlgorithm(Canonicalizer.ALGO_ID_C14N11_WITH_COMMENTS);
                        return new GenericAlgorithm(Canonicalizer.ALGO_ID_C14N_EXCL_OMIT_COMMENTS);
                    }
                    @Override
                    public String getDigestAlgorithmForDataObjsReferences() {
                        //return DigestMethod.SHA1;                       
                        return Constants.ALGO_ID_DIGEST_SHA1;
                    }
                    @Override
                    public String getDigestAlgorithmForReferenceProperties() {
                         return Constants.ALGO_ID_DIGEST_SHA1;
                    }
                    @Override
                    public String getDigestAlgorithmForTimeStampProperties() {
                        return Constants.ALGO_ID_DIGEST_SHA1;
                    }
                })              
                ;

I can't integrate tags SigPolicyQualifiers and description for the tag 
SigPolicyId.

Does anyone knows the solution?

By advance, thank you !
Regards.
```

Original issue reported on code.google.com by `sict...@gmail.com` on 2 Jan 2013 at 9:15

**Comment by jcaguilar40** [comment]
Dear Luis, I have a difference in the following node:
<xades:SignaturePolicyIdentifier>
<xades:SignaturePolicyId>
<xades:SigPolicyId>
<xades:Identifier>https://facturaelectronica.dian.gov.co/politicadefirma/v1/politicadefirmav1.pdf</xades:Identifier>
</xades:SigPolicyId>
<xades:SigPolicyHash>
<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
<ds:DigestValue>61fInBICBQOCBwuTwlaOZSi9HKc=</ds:DigestValue>
</xades:SigPolicyHash>
</xades:SignaturePolicyId>
</xades:SignaturePolicyIdentifier>

which is the correct one.


However with the library xades4j throws me this:
<xades:SignaturePolicyIdentifier>
<xades:SignaturePolicyId>
<xades:SigPolicyId>
<xades:Identifier>https://facturaelectronica.dian.gov.co/politicadefirma/v1/politicadefirmav1.pdf</xades:Identifier>
</xades:SigPolicyId>
<xades:SigPolicyHash>
<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<ds:DigestValue>UFXO4oIblU8Z986ahUrThOssg3Q=</ds:DigestValue>
</xades:SigPolicyHash>
</xades:SignaturePolicyId>
</xades:SignaturePolicyIdentifier>


The code in which I add the signature policy is the following:

        `SignaturePolicyInfoProvider policyInfoProvider = new SignaturePolicyInfoProvider() {
            public SignaturePolicyBase getSignaturePolicy() {
                return new SignaturePolicyIdentifierProperty(
                        new ObjectIdentifier("https://facturaelectronica.dian.gov.co/politicadefirma/v1/politicadefirmav1.pdf", IdentifierType.URI),
                        new ByteArrayInputStream("https://facturaelectronica.dian.gov.co/politicadefirma/v1/politicadefirmav1.pdf".getBytes()));
            }
        };

`

How could this problem be corrected in the digestvalue?

**Comment by luisgoncalves** [comment]
You're getting the bytes of the string `https://facturaelectronica.dian.gov.co/politicadefirma/v1/politicadefirmav1.pdf`... That's not what the [spec says](https://www.w3.org/TR/XAdES/#Syntax_for_XAdES_The_SignaturePolicyIdentifier_element):

>  The SigPolicyHash element contains the identifier of the hash algorithm and the hash value of the signature policy.

It refers to the actual contents of the policy file, not its URL.

**Comment by AK47-2020** [comment]
Hi, I see that see thread is old but could you clarify what "The SigPolicyHash element contains the identifier of the hash algorithm and the hash value of the signature policy" means? 

More precisely, in the following extract, over what is the hash computed?
              <xades:SignaturePolicyId>
                <xades:SigPolicyId>
                  <xades:Identifier>http://www.facturae.es/politica_de_firma_formato_facturae/politica_de_firma_formato_facturae_v3_1.pdf</xades:Identifier> // I take it that we add all the raw bytes to the hash input
                  <xades:Description>Política de firma electrónica para facturación electrónica con formato Facturae</xades:Description>
                </xades:SigPolicyId>
                <xades:SigPolicyHash>
                  <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha256"/>
                  <ds:DigestValue></ds:DigestValue>
                </xades:SigPolicyHash>
              </xades:SignaturePolicyId>
 
Except for the specific Spanish characters, what other canonicalization operation is required?
Thanks for your help.

**Comment by AK47-2020** [comment]
Luis, thanks for your swift reply. 

I computed "a/vDoueJq9zxWGCFwdsXdlXtkFSEek4XVtmlQCEDaE8=", but it doesn't verify with the ETSI validator. I may have done something wrong.

**Comment by AK47-2020** [comment]
That's an option but it should fail the official site verification.
Nevertheless, thanks again for your help!
