### ISSUE TITLE
<xades:SignerRole> and <xades:ClaimedRoles> tags are not added when signing using xadse4j 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [luisgoncalves/xades4j#81]
```
Dear Support Team,

I noticed that the below tags are not added in my xml when i signed it. It may 
be the reason of error during signature verification phase.

<xades:SignerRole><xades:ClaimedRoles><xades:ClaimedRole>Tedarikci</xades:Claime
dRole></xades:ClaimedRoles></xades:SignerRole>

Please tell me what may be reason and what i have to do so that these above 
mention tags can be add in signed documents.

Regards
Jay 
```

Original issue reported on code.google.com by `jay...@gmail.com` on 26 Mar 2014 at 8:28

**Comment by jcaguilar40** [comment]
Please Regards, Como lograstes añadir el rol de firma.
Atte José

**Comment by jcaguilar40** [comment]
Please Regards
How did you manage to add the signature role.

Thanks

**Comment by luisgoncalves** [comment]
You need to configure a custom [`SignaturePropertiesProvider`](https://github.com/luisgoncalves/xades4j/wiki/DefiningQualifyingProperties) to include additional properties.

Example [on lib unit tests](https://github.com/luisgoncalves/xades4j/blob/master/src/test/java/xades4j/production/SignerBESTest.java#L95).

**Comment by jcaguilar40** [comment]
Hi Luis.

Thanks for the reply.
It would be the same if I try to sign in XADES EPES?
Thanks.
Jose

**Comment by luisgoncalves** [comment]
Yes.
