### ISSUE TITLE
provide a way to specify TSA server without subclassing DefaultTimeStampTokenProvider

### ISSUE THREAD

**Issue by riskop** [luisgoncalves/xades4j#94]
Hello!

  I'd like to configure TSA server URL with minimal effort. As far as I see now it is only possible with either creating an implementation for the TimeStampTokenProvider interface or subclassing DefaultTimeStampTokenProvider class.

  If the constructor
DefaultTimeStampTokenProvider(MessageDigestEngineProvider messageDigestProvider, String tsaUrl) 
  were public instead of package private then it would be very easy to specify TSA, simply with the constructor.

  For example now I have to write this:
XadesSigner signer = new XadesTSigningProfile(keyingDataProvider)
.withTimeStampTokenProvider(MyTimeStampTokenProvider.class)
.withAlgorithmsProviderEx(ExclusiveC14nForTimestampsAlgorithmsProvider.class).newSigner();

  If the contructor were public I will write this:
XadesSigner signer = new XadesTSigningProfile(keyingDataProvider)
.withTimeStampTokenProvider(new DefaultTimeStampTokenProvider(new DefaultMessageDigestProvider(), "http://my.provider/tsa"))
.withAlgorithmsProviderEx(ExclusiveC14nForTimestampsAlgorithmsProvider.class).newSigner();

  What do you think about it?

**Comment by luisgoncalves** [comment]
Hello,

Yeah, that constructor should be public. That probably was an early decision that wasn't so good. In fact. [AuthenticatedTimeStampTokenProvider](https://github.com/luisgoncalves/xades4j/blob/master/src/main/java/xades4j/providers/impl/AuthenticatedTimeStampTokenProvider.java) has a public constructor to easily allow configuration...

**Comment by luisgoncalves** [comment]
- [ ] Add a type for TSA configuration, similar to `TSAHTtpAuthenticationData`
- [ ] Update [wiki page](https://github.com/luisgoncalves/xades4j/wiki/Timestamping)
