### ISSUE TITLE
Assinando outros documentos

### ISSUE THREAD

**Issue by SergioMendes93** [luisgoncalves/xades4j#95]
Antes de mais parabéns pela excelente biblioteca, está muito bem conseguida.
Gostava de saber se a ferramenta permite assinar .docx ou .pdf ou outro formato.
É que eu tentei inserir esses formatos no SignerBESTest e dá-me erro se usar esses formatos.
Se der, agradecia que explicasses como posso faze-lo nesse SignerBESTest por exemplo.
Obrigado

**Comment by luisgoncalves** [comment]
Esses formatos podem ser assinados se os recursos a assinar forem adicionados como referências externas (e.g. file URI ou URI relativo). Mais informação aqui: https://github.com/luisgoncalves/xades4j/wiki/DefiningSignedResources#dataobjectreference
