### ISSUE TITLE
showing milliseconds in SigningTimeVerificationException's message

### ISSUE THREAD

**Issue by riskop** [luisgoncalves/xades4j#97]
Hello Luis!

  Just a small issue. I got SigningTimeVerificationException when clocks were not in sync on our machines. That's fine, However the exception's message said something like this:

"Expected a signature time before 20160105 13:15:15 but actual signature time is 20160105 13:15:15"

  That was because the difference between the clocks was less than a second. And in this case the message is a bit misleading in my understanding.

  I think that the exception's message should be as accurate as the comparison. Since the comparison is based on milliseconds (SigningTimeVerifier.verify) the message should have at least millisecond resolution.

  What do you think?

  Best regards, Peter

**Comment by luisgoncalves** [comment]
The exception has all the accurate properties, but the message is indeed misleading. I guess [`SimpleDateFormat`](http://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html) should be used. Do you want to submit a PR?
