### ISSUE TITLE
Adding a generated signature from root element to a child element of same document

### ISSUE THREAD

**Issue by bellzebu** [luisgoncalves/xades4j#98]
Hi Luis,

thank you very much for your library, it is a very good implementation for Xades (the best, really) and it is very flexible.

My question is about sign an entery root element and add the result to a document element itself.

Having the following XML document

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<collection>
	<album>
		<title>Questions, unanswered</title>
		<artist>Steve and the flubberblubs</artist>
		<year>1989</year>
		<t:tracks xmlns:t="http://test.xades4j/tracks">
			<t:song tracknumber="1" length="4:05">
				<t:title>What do you know?</t:title>
				<t:artist>Steve and the flubberblubs</t:artist>
				<t:lastplayed>2006-10-17-08:31</t:lastplayed>
			</t:song>
		</t:tracks>
	</album>
</collection>
```
I would like to add the signature result to "album" element

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<collection>
	<album>
		<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="xmldsig-27afa3ae-bdf0-4d72-80ec-174f69970bef">
		....
		</ds:Signature>
		<title>Questions, unanswered</title>
		<artist>Steve and the flubberblubs</artist>
		<year>1989</year>
		<t:tracks xmlns:t="http://test.xades4j/tracks">
			<t:song tracknumber="1" length="4:05">
				<t:title>What do you know?</t:title>
				<t:artist>Steve and the flubberblubs</t:artist>
				<t:lastplayed>2006-10-17-08:31</t:lastplayed>
			</t:song>
		</t:tracks>
	</album>
</collection>
```

Is this possible?

I was reading https://github.com/luisgoncalves/xades4j/wiki/DefiningSignedResources#dataobjectreference looking for a solution to my question but i didn't found it (maybe for not understand it).

Thank you!

**Comment by luisgoncalves** [comment]
Thanks for the support!

regarding your question, you can use [this overload](http://luisgoncalves.github.io/xades4j/javadocs/1.3.1/reference/xades4j/production/XadesSigner.html#sign(xades4j.production.SignedDataObjects, org.w3c.dom.Node, xades4j.production.XadesSigner.SignatureAppendingStrategy)) on `XadesSigner` and supply a specific reference node. Something like:

```
Node albumNode = document.getXXXXX();
signer.sign(obj, albumNode, SignatureAppendingStrategies.AsFirstChild);
```

Or use the root element as reference node and implement a custom [`SignatureAppendingStrategy`](http://luisgoncalves.github.io/xades4j/javadocs/1.3.1/reference/xades4j/production/XadesSigner.SignatureAppendingStrategy.html).

Let me know if this helps.

**Comment by bellzebu** [comment]
A pleasure,  Luis!!

I found a solution but I don't know if is the best

```
XadesSigner signer = profile.newSigner();

DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
dbf.setNamespaceAware(true);

DocumentBuilder db = dbf.newDocumentBuilder();

Document doc = db.parse(new FileInputStream("/tmp/document.xml"));


DataObjectDesc dataObjRef = new DataObjectReference("").withTransform(new EnvelopedSignatureTransform());
XadesSignatureResult result = signer.sign(new SignedDataObjects(new DataObjectDesc[] { dataObjRef }), doc.getDocumentElement());

doc.getDocumentElement().getFirstChild().getNextSibling().appendChild(result.getSignature().getElement());

TransformerFactory tf = TransformerFactory.newInstance();
File outDir = new File("/tmp/");
FileOutputStream out = new FileOutputStream(new File(outDir, "result.xml"));
tf.newTransformer().transform(new DOMSource(doc), new StreamResult(out));
out.close();
```

I am going to try your proposed solution and let you know.

Thank you.

**Comment by bellzebu** [comment]
Great Luis,  using the overload on `XadesSigner` and `SignatureAppendingStrategies` works prefectly, and is more elegant than my previous solution.

Thank you very much for helping me.
